// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/resolution/v1/resolution.proto

package resolutionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolvePidRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Adapter namespace of the subject: "wiiu" | "3ds".
	Namespace     string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Pid           uint32 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvePidRequest) Reset() {
	*x = ResolvePidRequest{}
	mi := &file_proto_resolution_v1_resolution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvePidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvePidRequest) ProtoMessage() {}

func (x *ResolvePidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resolution_v1_resolution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvePidRequest.ProtoReflect.Descriptor instead.
func (*ResolvePidRequest) Descriptor() ([]byte, []int) {
	return file_proto_resolution_v1_resolution_proto_rawDescGZIP(), []int{0}
}

func (x *ResolvePidRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResolvePidRequest) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type ResolvePidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvePidResponse) Reset() {
	*x = ResolvePidResponse{}
	mi := &file_proto_resolution_v1_resolution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvePidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvePidResponse) ProtoMessage() {}

func (x *ResolvePidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resolution_v1_resolution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvePidResponse.ProtoReflect.Descriptor instead.
func (*ResolvePidResponse) Descriptor() ([]byte, []int) {
	return file_proto_resolution_v1_resolution_proto_rawDescGZIP(), []int{1}
}

func (x *ResolvePidResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *ResolvePidResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type ResolveAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveAccountRequest) Reset() {
	*x = ResolveAccountRequest{}
	mi := &file_proto_resolution_v1_resolution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAccountRequest) ProtoMessage() {}

func (x *ResolveAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resolution_v1_resolution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAccountRequest.ProtoReflect.Descriptor instead.
func (*ResolveAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_resolution_v1_resolution_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveAccountRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResolveAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type ResolveAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Pid           uint32                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveAccountResponse) Reset() {
	*x = ResolveAccountResponse{}
	mi := &file_proto_resolution_v1_resolution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAccountResponse) ProtoMessage() {}

func (x *ResolveAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resolution_v1_resolution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAccountResponse.ProtoReflect.Descriptor instead.
func (*ResolveAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_resolution_v1_resolution_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveAccountResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *ResolveAccountResponse) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

var File_proto_resolution_v1_resolution_proto protoreflect.FileDescriptor

const file_proto_resolution_v1_resolution_proto_rawDesc = "" +
	"\n" +
	"$proto/resolution/v1/resolution.proto\x12\x18nn_account.resolution.v1\"C\n" +
	"\x11ResolvePidRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\"I\n" +
	"\x12ResolvePidResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\"T\n" +
	"\x15ResolveAccountRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\"@\n" +
	"\x16ResolveAccountResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid2\xea\x01\n" +
	"\n" +
	"Resolution\x12g\n" +
	"\n" +
	"ResolvePid\x12+.nn_account.resolution.v1.ResolvePidRequest\x1a,.nn_account.resolution.v1.ResolvePidResponse\x12s\n" +
	"\x0eResolveAccount\x12/.nn_account.resolution.v1.ResolveAccountRequest\x1a0.nn_account.resolution.v1.ResolveAccountResponseB5Z3openpak/nn-account/proto/resolution/v1;resolutionv1b\x06proto3"

var (
	file_proto_resolution_v1_resolution_proto_rawDescOnce sync.Once
	file_proto_resolution_v1_resolution_proto_rawDescData []byte
)

func file_proto_resolution_v1_resolution_proto_rawDescGZIP() []byte {
	file_proto_resolution_v1_resolution_proto_rawDescOnce.Do(func() {
		file_proto_resolution_v1_resolution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_resolution_v1_resolution_proto_rawDesc), len(file_proto_resolution_v1_resolution_proto_rawDesc)))
	})
	return file_proto_resolution_v1_resolution_proto_rawDescData
}

var file_proto_resolution_v1_resolution_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_resolution_v1_resolution_proto_goTypes = []any{
	(*ResolvePidRequest)(nil),      // 0: nn_account.resolution.v1.ResolvePidRequest
	(*ResolvePidResponse)(nil),     // 1: nn_account.resolution.v1.ResolvePidResponse
	(*ResolveAccountRequest)(nil),  // 2: nn_account.resolution.v1.ResolveAccountRequest
	(*ResolveAccountResponse)(nil), // 3: nn_account.resolution.v1.ResolveAccountResponse
}
var file_proto_resolution_v1_resolution_proto_depIdxs = []int32{
	0, // 0: nn_account.resolution.v1.Resolution.ResolvePid:input_type -> nn_account.resolution.v1.ResolvePidRequest
	2, // 1: nn_account.resolution.v1.Resolution.ResolveAccount:input_type -> nn_account.resolution.v1.ResolveAccountRequest
	1, // 2: nn_account.resolution.v1.Resolution.ResolvePid:output_type -> nn_account.resolution.v1.ResolvePidResponse
	3, // 3: nn_account.resolution.v1.Resolution.ResolveAccount:output_type -> nn_account.resolution.v1.ResolveAccountResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_resolution_v1_resolution_proto_init() }
func file_proto_resolution_v1_resolution_proto_init() {
	if File_proto_resolution_v1_resolution_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_resolution_v1_resolution_proto_rawDesc), len(file_proto_resolution_v1_resolution_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_resolution_v1_resolution_proto_goTypes,
		DependencyIndexes: file_proto_resolution_v1_resolution_proto_depIdxs,
		MessageInfos:      file_proto_resolution_v1_resolution_proto_msgTypes,
	}.Build()
	File_proto_resolution_v1_resolution_proto = out.File
	file_proto_resolution_v1_resolution_proto_goTypes = nil
	file_proto_resolution_v1_resolution_proto_depIdxs = nil
}
