// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/resolution/v1/resolution.proto

package resolutionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Resolution_ResolvePid_FullMethodName     = "/nn_account.resolution.v1.Resolution/ResolvePid"
	Resolution_ResolveAccount_FullMethodName = "/nn_account.resolution.v1.Resolution/ResolveAccount"
)

// ResolutionClient is the client API for Resolution service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Nintendo identity resolution for internal consumers (PRD §7): maps a
// console PID to the core account it is linked to. Provided by nn-account —
// consumers never address the core by PID.
type ResolutionClient interface {
	ResolvePid(ctx context.Context, in *ResolvePidRequest, opts ...grpc.CallOption) (*ResolvePidResponse, error)
	// Reverse mapping for rendering friend lists (account -> PID).
	ResolveAccount(ctx context.Context, in *ResolveAccountRequest, opts ...grpc.CallOption) (*ResolveAccountResponse, error)
}

type resolutionClient struct {
	cc grpc.ClientConnInterface
}

func NewResolutionClient(cc grpc.ClientConnInterface) ResolutionClient {
	return &resolutionClient{cc}
}

func (c *resolutionClient) ResolvePid(ctx context.Context, in *ResolvePidRequest, opts ...grpc.CallOption) (*ResolvePidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolvePidResponse)
	err := c.cc.Invoke(ctx, Resolution_ResolvePid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resolutionClient) ResolveAccount(ctx context.Context, in *ResolveAccountRequest, opts ...grpc.CallOption) (*ResolveAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveAccountResponse)
	err := c.cc.Invoke(ctx, Resolution_ResolveAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResolutionServer is the server API for Resolution service.
// All implementations must embed UnimplementedResolutionServer
// for forward compatibility.
//
// Nintendo identity resolution for internal consumers (PRD §7): maps a
// console PID to the core account it is linked to. Provided by nn-account —
// consumers never address the core by PID.
type ResolutionServer interface {
	ResolvePid(context.Context, *ResolvePidRequest) (*ResolvePidResponse, error)
	// Reverse mapping for rendering friend lists (account -> PID).
	ResolveAccount(context.Context, *ResolveAccountRequest) (*ResolveAccountResponse, error)
	mustEmbedUnimplementedResolutionServer()
}

// UnimplementedResolutionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResolutionServer struct{}

func (UnimplementedResolutionServer) ResolvePid(context.Context, *ResolvePidRequest) (*ResolvePidResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolvePid not implemented")
}
func (UnimplementedResolutionServer) ResolveAccount(context.Context, *ResolveAccountRequest) (*ResolveAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveAccount not implemented")
}
func (UnimplementedResolutionServer) mustEmbedUnimplementedResolutionServer() {}
func (UnimplementedResolutionServer) testEmbeddedByValue()                    {}

// UnsafeResolutionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResolutionServer will
// result in compilation errors.
type UnsafeResolutionServer interface {
	mustEmbedUnimplementedResolutionServer()
}

func RegisterResolutionServer(s grpc.ServiceRegistrar, srv ResolutionServer) {
	// If the following call panics, it indicates UnimplementedResolutionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Resolution_ServiceDesc, srv)
}

func _Resolution_ResolvePid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolvePidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResolutionServer).ResolvePid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Resolution_ResolvePid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResolutionServer).ResolvePid(ctx, req.(*ResolvePidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resolution_ResolveAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResolutionServer).ResolveAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Resolution_ResolveAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResolutionServer).ResolveAccount(ctx, req.(*ResolveAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Resolution_ServiceDesc is the grpc.ServiceDesc for Resolution service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Resolution_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nn_account.resolution.v1.Resolution",
	HandlerType: (*ResolutionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolvePid",
			Handler:    _Resolution_ResolvePid_Handler,
		},
		{
			MethodName: "ResolveAccount",
			Handler:    _Resolution_ResolveAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/resolution/v1/resolution.proto",
}
