// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: openpak/account/v1/account.proto

package accountv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountStatus int32

const (
	AccountStatus_ACCOUNT_STATUS_UNSPECIFIED      AccountStatus = 0
	AccountStatus_ACCOUNT_STATUS_ACTIVE           AccountStatus = 1
	AccountStatus_ACCOUNT_STATUS_BANNED           AccountStatus = 2
	AccountStatus_ACCOUNT_STATUS_DELETION_PENDING AccountStatus = 3
	AccountStatus_ACCOUNT_STATUS_DELETED          AccountStatus = 4
)

// Enum value maps for AccountStatus.
var (
	AccountStatus_name = map[int32]string{
		0: "ACCOUNT_STATUS_UNSPECIFIED",
		1: "ACCOUNT_STATUS_ACTIVE",
		2: "ACCOUNT_STATUS_BANNED",
		3: "ACCOUNT_STATUS_DELETION_PENDING",
		4: "ACCOUNT_STATUS_DELETED",
	}
	AccountStatus_value = map[string]int32{
		"ACCOUNT_STATUS_UNSPECIFIED":      0,
		"ACCOUNT_STATUS_ACTIVE":           1,
		"ACCOUNT_STATUS_BANNED":           2,
		"ACCOUNT_STATUS_DELETION_PENDING": 3,
		"ACCOUNT_STATUS_DELETED":          4,
	}
)

func (x AccountStatus) Enum() *AccountStatus {
	p := new(AccountStatus)
	*p = x
	return p
}

func (x AccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_openpak_account_v1_account_proto_enumTypes[0].Descriptor()
}

func (AccountStatus) Type() protoreflect.EnumType {
	return &file_openpak_account_v1_account_proto_enumTypes[0]
}

func (x AccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountStatus.Descriptor instead.
func (AccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_openpak_account_v1_account_proto_rawDescGZIP(), []int{0}
}

type LinkState int32

const (
	LinkState_LINK_STATE_UNSPECIFIED LinkState = 0
	LinkState_LINK_STATE_PENDING     LinkState = 1
	LinkState_LINK_STATE_ACTIVE      LinkState = 2
	LinkState_LINK_STATE_REVOKING    LinkState = 3
	LinkState_LINK_STATE_REVOKED     LinkState = 4
)

// Enum value maps for LinkState.
var (
	LinkState_name = map[int32]string{
		0: "LINK_STATE_UNSPECIFIED",
		1: "LINK_STATE_PENDING",
		2: "LINK_STATE_ACTIVE",
		3: "LINK_STATE_REVOKING",
		4: "LINK_STATE_REVOKED",
	}
	LinkState_value = map[string]int32{
		"LINK_STATE_UNSPECIFIED": 0,
		"LINK_STATE_PENDING":     1,
		"LINK_STATE_ACTIVE":      2,
		"LINK_STATE_REVOKING":    3,
		"LINK_STATE_REVOKED":     4,
	}
)

func (x LinkState) Enum() *LinkState {
	p := new(LinkState)
	*p = x
	return p
}

func (x LinkState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LinkState) Descriptor() protoreflect.EnumDescriptor {
	return file_openpak_account_v1_account_proto_enumTypes[1].Descriptor()
}

func (LinkState) Type() protoreflect.EnumType {
	return &file_openpak_account_v1_account_proto_enumTypes[1]
}

func (x LinkState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LinkState.Descriptor instead.
func (LinkState) EnumDescriptor() ([]byte, []int) {
	return file_openpak_account_v1_account_proto_rawDescGZIP(), []int{1}
}

type VerifyPasswordByIDRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CallerNamespace string                 `protobuf:"bytes,1,opt,name=caller_namespace,json=callerNamespace,proto3" json:"caller_namespace,omitempty"`
	Purpose         string                 `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`
	AccountId       string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Password        string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VerifyPasswordByIDRequest) Reset() {
	*x = VerifyPasswordByIDRequest{}
	mi := &file_openpak_account_v1_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPasswordByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPasswordByIDRequest) ProtoMessage() {}

func (x *VerifyPasswordByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPasswordByIDRequest.ProtoReflect.Descriptor instead.
func (*VerifyPasswordByIDRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_account_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyPasswordByIDRequest) GetCallerNamespace() string {
	if x != nil {
		return x.CallerNamespace
	}
	return ""
}

func (x *VerifyPasswordByIDRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *VerifyPasswordByIDRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *VerifyPasswordByIDRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type VerifyPasswordRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CallerNamespace string                 `protobuf:"bytes,1,opt,name=caller_namespace,json=callerNamespace,proto3" json:"caller_namespace,omitempty"` // adapter namespace requesting verification
	Purpose         string                 `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`                                        // e.g. "console_login", "link"
	Email           string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password        string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VerifyPasswordRequest) Reset() {
	*x = VerifyPasswordRequest{}
	mi := &file_openpak_account_v1_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPasswordRequest) ProtoMessage() {}

func (x *VerifyPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPasswordRequest.ProtoReflect.Descriptor instead.
func (*VerifyPasswordRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_account_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyPasswordRequest) GetCallerNamespace() string {
	if x != nil {
		return x.CallerNamespace
	}
	return ""
}

func (x *VerifyPasswordRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *VerifyPasswordRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerifyPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type VerifyPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Status        AccountStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=openpak.account.v1.AccountStatus" json:"status,omitempty"`
	EmailVerified bool                   `protobuf:"varint,3,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	// Profile facts the console's user object requires; empty when never collected.
	Country       string `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Birthday      string `protobuf:"bytes,5,opt,name=birthday,proto3" json:"birthday,omitempty"` // ISO 8601 date, e.g. "1990-01-01"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPasswordResponse) Reset() {
	*x = VerifyPasswordResponse{}
	mi := &file_openpak_account_v1_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPasswordResponse) ProtoMessage() {}

func (x *VerifyPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPasswordResponse.ProtoReflect.Descriptor instead.
func (*VerifyPasswordResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_account_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyPasswordResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *VerifyPasswordResponse) GetStatus() AccountStatus {
	if x != nil {
		return x.Status
	}
	return AccountStatus_ACCOUNT_STATUS_UNSPECIFIED
}

func (x *VerifyPasswordResponse) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *VerifyPasswordResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *VerifyPasswordResponse) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_openpak_account_v1_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_account_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Status        AccountStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=openpak.account.v1.AccountStatus" json:"status,omitempty"`
	EmailVerified bool                   `protobuf:"varint,3,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	Birthday      string                 `protobuf:"bytes,6,opt,name=birthday,proto3" json:"birthday,omitempty"` // ISO 8601 date, e.g. "1990-01-01"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_openpak_account_v1_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_account_proto_rawDescGZIP(), []int{4}
}

func (x *GetAccountResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetAccountResponse) GetStatus() AccountStatus {
	if x != nil {
		return x.Status
	}
	return AccountStatus_ACCOUNT_STATUS_UNSPECIFIED
}

func (x *GetAccountResponse) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *GetAccountResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *GetAccountResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *GetAccountResponse) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

type SetAdapterCredentialRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CallerNamespace string                 `protobuf:"bytes,1,opt,name=caller_namespace,json=callerNamespace,proto3" json:"caller_namespace,omitempty"`
	Purpose         string                 `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`
	AccountId       string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Secret          string                 `protobuf:"bytes,4,opt,name=secret,proto3" json:"secret,omitempty"` // adapter-forwarded secret; hashed server-side, never logged
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetAdapterCredentialRequest) Reset() {
	*x = SetAdapterCredentialRequest{}
	mi := &file_openpak_account_v1_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAdapterCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAdapterCredentialRequest) ProtoMessage() {}

func (x *SetAdapterCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAdapterCredentialRequest.ProtoReflect.Descriptor instead.
func (*SetAdapterCredentialRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_account_proto_rawDescGZIP(), []int{5}
}

func (x *SetAdapterCredentialRequest) GetCallerNamespace() string {
	if x != nil {
		return x.CallerNamespace
	}
	return ""
}

func (x *SetAdapterCredentialRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *SetAdapterCredentialRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *SetAdapterCredentialRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type SetAdapterCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAdapterCredentialResponse) Reset() {
	*x = SetAdapterCredentialResponse{}
	mi := &file_openpak_account_v1_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAdapterCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAdapterCredentialResponse) ProtoMessage() {}

func (x *SetAdapterCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAdapterCredentialResponse.ProtoReflect.Descriptor instead.
func (*SetAdapterCredentialResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_account_proto_rawDescGZIP(), []int{6}
}

type RequestAccountDeletionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CallerNamespace string                 `protobuf:"bytes,1,opt,name=caller_namespace,json=callerNamespace,proto3" json:"caller_namespace,omitempty"`
	Purpose         string                 `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`
	AccountId       string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RequestAccountDeletionRequest) Reset() {
	*x = RequestAccountDeletionRequest{}
	mi := &file_openpak_account_v1_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAccountDeletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAccountDeletionRequest) ProtoMessage() {}

func (x *RequestAccountDeletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAccountDeletionRequest.ProtoReflect.Descriptor instead.
func (*RequestAccountDeletionRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_account_proto_rawDescGZIP(), []int{7}
}

func (x *RequestAccountDeletionRequest) GetCallerNamespace() string {
	if x != nil {
		return x.CallerNamespace
	}
	return ""
}

func (x *RequestAccountDeletionRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *RequestAccountDeletionRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type RequestAccountDeletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestAccountDeletionResponse) Reset() {
	*x = RequestAccountDeletionResponse{}
	mi := &file_openpak_account_v1_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAccountDeletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAccountDeletionResponse) ProtoMessage() {}

func (x *RequestAccountDeletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAccountDeletionResponse.ProtoReflect.Descriptor instead.
func (*RequestAccountDeletionResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_account_proto_rawDescGZIP(), []int{8}
}

type VerifyAdapterCredentialRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CallerNamespace string                 `protobuf:"bytes,1,opt,name=caller_namespace,json=callerNamespace,proto3" json:"caller_namespace,omitempty"`
	Purpose         string                 `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`
	AccountId       string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Secret          string                 `protobuf:"bytes,4,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VerifyAdapterCredentialRequest) Reset() {
	*x = VerifyAdapterCredentialRequest{}
	mi := &file_openpak_account_v1_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAdapterCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAdapterCredentialRequest) ProtoMessage() {}

func (x *VerifyAdapterCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAdapterCredentialRequest.ProtoReflect.Descriptor instead.
func (*VerifyAdapterCredentialRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_account_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyAdapterCredentialRequest) GetCallerNamespace() string {
	if x != nil {
		return x.CallerNamespace
	}
	return ""
}

func (x *VerifyAdapterCredentialRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *VerifyAdapterCredentialRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *VerifyAdapterCredentialRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type VerifyAdapterCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Status        AccountStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=openpak.account.v1.AccountStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAdapterCredentialResponse) Reset() {
	*x = VerifyAdapterCredentialResponse{}
	mi := &file_openpak_account_v1_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAdapterCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAdapterCredentialResponse) ProtoMessage() {}

func (x *VerifyAdapterCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAdapterCredentialResponse.ProtoReflect.Descriptor instead.
func (*VerifyAdapterCredentialResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_account_proto_rawDescGZIP(), []int{10}
}

func (x *VerifyAdapterCredentialResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyAdapterCredentialResponse) GetStatus() AccountStatus {
	if x != nil {
		return x.Status
	}
	return AccountStatus_ACCOUNT_STATUS_UNSPECIFIED
}

type ReserveLinkRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountId      string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Namespace      string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	SubjectId      string                 `protobuf:"bytes,3,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReserveLinkRequest) Reset() {
	*x = ReserveLinkRequest{}
	mi := &file_openpak_account_v1_account_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveLinkRequest) ProtoMessage() {}

func (x *ReserveLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_account_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveLinkRequest.ProtoReflect.Descriptor instead.
func (*ReserveLinkRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_account_proto_rawDescGZIP(), []int{11}
}

func (x *ReserveLinkRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ReserveLinkRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ReserveLinkRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *ReserveLinkRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type ReserveLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkId        string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	State         LinkState              `protobuf:"varint,2,opt,name=state,proto3,enum=openpak.account.v1.LinkState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveLinkResponse) Reset() {
	*x = ReserveLinkResponse{}
	mi := &file_openpak_account_v1_account_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveLinkResponse) ProtoMessage() {}

func (x *ReserveLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_account_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveLinkResponse.ProtoReflect.Descriptor instead.
func (*ReserveLinkResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_account_proto_rawDescGZIP(), []int{12}
}

func (x *ReserveLinkResponse) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *ReserveLinkResponse) GetState() LinkState {
	if x != nil {
		return x.State
	}
	return LinkState_LINK_STATE_UNSPECIFIED
}

type ActivateLinkRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LinkId         string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ActivateLinkRequest) Reset() {
	*x = ActivateLinkRequest{}
	mi := &file_openpak_account_v1_account_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateLinkRequest) ProtoMessage() {}

func (x *ActivateLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_account_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateLinkRequest.ProtoReflect.Descriptor instead.
func (*ActivateLinkRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_account_proto_rawDescGZIP(), []int{13}
}

func (x *ActivateLinkRequest) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *ActivateLinkRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type ActivateLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         LinkState              `protobuf:"varint,1,opt,name=state,proto3,enum=openpak.account.v1.LinkState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateLinkResponse) Reset() {
	*x = ActivateLinkResponse{}
	mi := &file_openpak_account_v1_account_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateLinkResponse) ProtoMessage() {}

func (x *ActivateLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_account_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateLinkResponse.ProtoReflect.Descriptor instead.
func (*ActivateLinkResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_account_proto_rawDescGZIP(), []int{14}
}

func (x *ActivateLinkResponse) GetState() LinkState {
	if x != nil {
		return x.State
	}
	return LinkState_LINK_STATE_UNSPECIFIED
}

type UnlinkLinkRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LinkId         string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UnlinkLinkRequest) Reset() {
	*x = UnlinkLinkRequest{}
	mi := &file_openpak_account_v1_account_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkLinkRequest) ProtoMessage() {}

func (x *UnlinkLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_account_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkLinkRequest.ProtoReflect.Descriptor instead.
func (*UnlinkLinkRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_account_proto_rawDescGZIP(), []int{15}
}

func (x *UnlinkLinkRequest) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *UnlinkLinkRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type UnlinkLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         LinkState              `protobuf:"varint,1,opt,name=state,proto3,enum=openpak.account.v1.LinkState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkLinkResponse) Reset() {
	*x = UnlinkLinkResponse{}
	mi := &file_openpak_account_v1_account_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkLinkResponse) ProtoMessage() {}

func (x *UnlinkLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_account_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkLinkResponse.ProtoReflect.Descriptor instead.
func (*UnlinkLinkResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_account_proto_rawDescGZIP(), []int{16}
}

func (x *UnlinkLinkResponse) GetState() LinkState {
	if x != nil {
		return x.State
	}
	return LinkState_LINK_STATE_UNSPECIFIED
}

type GetLinkBySubjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	SubjectId     string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkBySubjectRequest) Reset() {
	*x = GetLinkBySubjectRequest{}
	mi := &file_openpak_account_v1_account_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkBySubjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkBySubjectRequest) ProtoMessage() {}

func (x *GetLinkBySubjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_account_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkBySubjectRequest.ProtoReflect.Descriptor instead.
func (*GetLinkBySubjectRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_account_proto_rawDescGZIP(), []int{17}
}

func (x *GetLinkBySubjectRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetLinkBySubjectRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

type GetActiveLinkByAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveLinkByAccountRequest) Reset() {
	*x = GetActiveLinkByAccountRequest{}
	mi := &file_openpak_account_v1_account_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveLinkByAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveLinkByAccountRequest) ProtoMessage() {}

func (x *GetActiveLinkByAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_account_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveLinkByAccountRequest.ProtoReflect.Descriptor instead.
func (*GetActiveLinkByAccountRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_account_proto_rawDescGZIP(), []int{18}
}

func (x *GetActiveLinkByAccountRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetActiveLinkByAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetLinkBySubjectResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	LinkId    string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	AccountId string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	State     LinkState              `protobuf:"varint,3,opt,name=state,proto3,enum=openpak.account.v1.LinkState" json:"state,omitempty"`
	// Populated only by GetActiveLinkByAccount (the subject is the lookup key
	// on GetLinkBySubject).
	SubjectId     string `protobuf:"bytes,4,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkBySubjectResponse) Reset() {
	*x = GetLinkBySubjectResponse{}
	mi := &file_openpak_account_v1_account_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkBySubjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkBySubjectResponse) ProtoMessage() {}

func (x *GetLinkBySubjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_account_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkBySubjectResponse.ProtoReflect.Descriptor instead.
func (*GetLinkBySubjectResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_account_proto_rawDescGZIP(), []int{19}
}

func (x *GetLinkBySubjectResponse) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *GetLinkBySubjectResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetLinkBySubjectResponse) GetState() LinkState {
	if x != nil {
		return x.State
	}
	return LinkState_LINK_STATE_UNSPECIFIED
}

func (x *GetLinkBySubjectResponse) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

var File_openpak_account_v1_account_proto protoreflect.FileDescriptor

const file_openpak_account_v1_account_proto_rawDesc = "" +
	"\n" +
	" openpak/account/v1/account.proto\x12\x12openpak.account.v1\"\x9b\x01\n" +
	"\x19VerifyPasswordByIDRequest\x12)\n" +
	"\x10caller_namespace\x18\x01 \x01(\tR\x0fcallerNamespace\x12\x18\n" +
	"\apurpose\x18\x02 \x01(\tR\apurpose\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"\x8e\x01\n" +
	"\x15VerifyPasswordRequest\x12)\n" +
	"\x10caller_namespace\x18\x01 \x01(\tR\x0fcallerNamespace\x12\x18\n" +
	"\apurpose\x18\x02 \x01(\tR\apurpose\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"\xcf\x01\n" +
	"\x16VerifyPasswordResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x129\n" +
	"\x06status\x18\x02 \x01(\x0e2!.openpak.account.v1.AccountStatusR\x06status\x12%\n" +
	"\x0eemail_verified\x18\x03 \x01(\bR\remailVerified\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x1a\n" +
	"\bbirthday\x18\x05 \x01(\tR\bbirthday\"2\n" +
	"\x11GetAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"\xee\x01\n" +
	"\x12GetAccountResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x129\n" +
	"\x06status\x18\x02 \x01(\x0e2!.openpak.account.v1.AccountStatusR\x06status\x12%\n" +
	"\x0eemail_verified\x18\x03 \x01(\bR\remailVerified\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12\x1a\n" +
	"\bbirthday\x18\x06 \x01(\tR\bbirthday\"\x99\x01\n" +
	"\x1bSetAdapterCredentialRequest\x12)\n" +
	"\x10caller_namespace\x18\x01 \x01(\tR\x0fcallerNamespace\x12\x18\n" +
	"\apurpose\x18\x02 \x01(\tR\apurpose\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12\x16\n" +
	"\x06secret\x18\x04 \x01(\tR\x06secret\"\x1e\n" +
	"\x1cSetAdapterCredentialResponse\"\x83\x01\n" +
	"\x1dRequestAccountDeletionRequest\x12)\n" +
	"\x10caller_namespace\x18\x01 \x01(\tR\x0fcallerNamespace\x12\x18\n" +
	"\apurpose\x18\x02 \x01(\tR\apurpose\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\" \n" +
	"\x1eRequestAccountDeletionResponse\"\x9c\x01\n" +
	"\x1eVerifyAdapterCredentialRequest\x12)\n" +
	"\x10caller_namespace\x18\x01 \x01(\tR\x0fcallerNamespace\x12\x18\n" +
	"\apurpose\x18\x02 \x01(\tR\apurpose\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12\x16\n" +
	"\x06secret\x18\x04 \x01(\tR\x06secret\"r\n" +
	"\x1fVerifyAdapterCredentialResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x129\n" +
	"\x06status\x18\x02 \x01(\x0e2!.openpak.account.v1.AccountStatusR\x06status\"\x99\x01\n" +
	"\x12ReserveLinkRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x03 \x01(\tR\tsubjectId\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"c\n" +
	"\x13ReserveLinkResponse\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x123\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1d.openpak.account.v1.LinkStateR\x05state\"W\n" +
	"\x13ActivateLinkRequest\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\"K\n" +
	"\x14ActivateLinkResponse\x123\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1d.openpak.account.v1.LinkStateR\x05state\"U\n" +
	"\x11UnlinkLinkRequest\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\"I\n" +
	"\x12UnlinkLinkResponse\x123\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1d.openpak.account.v1.LinkStateR\x05state\"V\n" +
	"\x17GetLinkBySubjectRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\"\\\n" +
	"\x1dGetActiveLinkByAccountRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\"\xa6\x01\n" +
	"\x18GetLinkBySubjectResponse\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x123\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1d.openpak.account.v1.LinkStateR\x05state\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x04 \x01(\tR\tsubjectId*\xa6\x01\n" +
	"\rAccountStatus\x12\x1e\n" +
	"\x1aACCOUNT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ACCOUNT_STATUS_ACTIVE\x10\x01\x12\x19\n" +
	"\x15ACCOUNT_STATUS_BANNED\x10\x02\x12#\n" +
	"\x1fACCOUNT_STATUS_DELETION_PENDING\x10\x03\x12\x1a\n" +
	"\x16ACCOUNT_STATUS_DELETED\x10\x04*\x87\x01\n" +
	"\tLinkState\x12\x1a\n" +
	"\x16LINK_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12LINK_STATE_PENDING\x10\x01\x12\x15\n" +
	"\x11LINK_STATE_ACTIVE\x10\x02\x12\x17\n" +
	"\x13LINK_STATE_REVOKING\x10\x03\x12\x16\n" +
	"\x12LINK_STATE_REVOKED\x10\x042\xc2\x05\n" +
	"\bIdentity\x12g\n" +
	"\x0eVerifyPassword\x12).openpak.account.v1.VerifyPasswordRequest\x1a*.openpak.account.v1.VerifyPasswordResponse\x12o\n" +
	"\x12VerifyPasswordByID\x12-.openpak.account.v1.VerifyPasswordByIDRequest\x1a*.openpak.account.v1.VerifyPasswordResponse\x12y\n" +
	"\x14SetAdapterCredential\x12/.openpak.account.v1.SetAdapterCredentialRequest\x1a0.openpak.account.v1.SetAdapterCredentialResponse\x12\x7f\n" +
	"\x16RequestAccountDeletion\x121.openpak.account.v1.RequestAccountDeletionRequest\x1a2.openpak.account.v1.RequestAccountDeletionResponse\x12\x82\x01\n" +
	"\x17VerifyAdapterCredential\x122.openpak.account.v1.VerifyAdapterCredentialRequest\x1a3.openpak.account.v1.VerifyAdapterCredentialResponse\x12[\n" +
	"\n" +
	"GetAccount\x12%.openpak.account.v1.GetAccountRequest\x1a&.openpak.account.v1.GetAccountResponse2\x91\x04\n" +
	"\x05Links\x12^\n" +
	"\vReserveLink\x12&.openpak.account.v1.ReserveLinkRequest\x1a'.openpak.account.v1.ReserveLinkResponse\x12a\n" +
	"\fActivateLink\x12'.openpak.account.v1.ActivateLinkRequest\x1a(.openpak.account.v1.ActivateLinkResponse\x12[\n" +
	"\n" +
	"UnlinkLink\x12%.openpak.account.v1.UnlinkLinkRequest\x1a&.openpak.account.v1.UnlinkLinkResponse\x12m\n" +
	"\x10GetLinkBySubject\x12+.openpak.account.v1.GetLinkBySubjectRequest\x1a,.openpak.account.v1.GetLinkBySubjectResponse\x12y\n" +
	"\x16GetActiveLinkByAccount\x121.openpak.account.v1.GetActiveLinkByAccountRequest\x1a,.openpak.account.v1.GetLinkBySubjectResponseB4Z2openpak/account/proto/openpak/account/v1;accountv1b\x06proto3"

var (
	file_openpak_account_v1_account_proto_rawDescOnce sync.Once
	file_openpak_account_v1_account_proto_rawDescData []byte
)

func file_openpak_account_v1_account_proto_rawDescGZIP() []byte {
	file_openpak_account_v1_account_proto_rawDescOnce.Do(func() {
		file_openpak_account_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openpak_account_v1_account_proto_rawDesc), len(file_openpak_account_v1_account_proto_rawDesc)))
	})
	return file_openpak_account_v1_account_proto_rawDescData
}

var file_openpak_account_v1_account_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_openpak_account_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_openpak_account_v1_account_proto_goTypes = []any{
	(AccountStatus)(0),                      // 0: openpak.account.v1.AccountStatus
	(LinkState)(0),                          // 1: openpak.account.v1.LinkState
	(*VerifyPasswordByIDRequest)(nil),       // 2: openpak.account.v1.VerifyPasswordByIDRequest
	(*VerifyPasswordRequest)(nil),           // 3: openpak.account.v1.VerifyPasswordRequest
	(*VerifyPasswordResponse)(nil),          // 4: openpak.account.v1.VerifyPasswordResponse
	(*GetAccountRequest)(nil),               // 5: openpak.account.v1.GetAccountRequest
	(*GetAccountResponse)(nil),              // 6: openpak.account.v1.GetAccountResponse
	(*SetAdapterCredentialRequest)(nil),     // 7: openpak.account.v1.SetAdapterCredentialRequest
	(*SetAdapterCredentialResponse)(nil),    // 8: openpak.account.v1.SetAdapterCredentialResponse
	(*RequestAccountDeletionRequest)(nil),   // 9: openpak.account.v1.RequestAccountDeletionRequest
	(*RequestAccountDeletionResponse)(nil),  // 10: openpak.account.v1.RequestAccountDeletionResponse
	(*VerifyAdapterCredentialRequest)(nil),  // 11: openpak.account.v1.VerifyAdapterCredentialRequest
	(*VerifyAdapterCredentialResponse)(nil), // 12: openpak.account.v1.VerifyAdapterCredentialResponse
	(*ReserveLinkRequest)(nil),              // 13: openpak.account.v1.ReserveLinkRequest
	(*ReserveLinkResponse)(nil),             // 14: openpak.account.v1.ReserveLinkResponse
	(*ActivateLinkRequest)(nil),             // 15: openpak.account.v1.ActivateLinkRequest
	(*ActivateLinkResponse)(nil),            // 16: openpak.account.v1.ActivateLinkResponse
	(*UnlinkLinkRequest)(nil),               // 17: openpak.account.v1.UnlinkLinkRequest
	(*UnlinkLinkResponse)(nil),              // 18: openpak.account.v1.UnlinkLinkResponse
	(*GetLinkBySubjectRequest)(nil),         // 19: openpak.account.v1.GetLinkBySubjectRequest
	(*GetActiveLinkByAccountRequest)(nil),   // 20: openpak.account.v1.GetActiveLinkByAccountRequest
	(*GetLinkBySubjectResponse)(nil),        // 21: openpak.account.v1.GetLinkBySubjectResponse
}
var file_openpak_account_v1_account_proto_depIdxs = []int32{
	0,  // 0: openpak.account.v1.VerifyPasswordResponse.status:type_name -> openpak.account.v1.AccountStatus
	0,  // 1: openpak.account.v1.GetAccountResponse.status:type_name -> openpak.account.v1.AccountStatus
	0,  // 2: openpak.account.v1.VerifyAdapterCredentialResponse.status:type_name -> openpak.account.v1.AccountStatus
	1,  // 3: openpak.account.v1.ReserveLinkResponse.state:type_name -> openpak.account.v1.LinkState
	1,  // 4: openpak.account.v1.ActivateLinkResponse.state:type_name -> openpak.account.v1.LinkState
	1,  // 5: openpak.account.v1.UnlinkLinkResponse.state:type_name -> openpak.account.v1.LinkState
	1,  // 6: openpak.account.v1.GetLinkBySubjectResponse.state:type_name -> openpak.account.v1.LinkState
	3,  // 7: openpak.account.v1.Identity.VerifyPassword:input_type -> openpak.account.v1.VerifyPasswordRequest
	2,  // 8: openpak.account.v1.Identity.VerifyPasswordByID:input_type -> openpak.account.v1.VerifyPasswordByIDRequest
	7,  // 9: openpak.account.v1.Identity.SetAdapterCredential:input_type -> openpak.account.v1.SetAdapterCredentialRequest
	9,  // 10: openpak.account.v1.Identity.RequestAccountDeletion:input_type -> openpak.account.v1.RequestAccountDeletionRequest
	11, // 11: openpak.account.v1.Identity.VerifyAdapterCredential:input_type -> openpak.account.v1.VerifyAdapterCredentialRequest
	5,  // 12: openpak.account.v1.Identity.GetAccount:input_type -> openpak.account.v1.GetAccountRequest
	13, // 13: openpak.account.v1.Links.ReserveLink:input_type -> openpak.account.v1.ReserveLinkRequest
	15, // 14: openpak.account.v1.Links.ActivateLink:input_type -> openpak.account.v1.ActivateLinkRequest
	17, // 15: openpak.account.v1.Links.UnlinkLink:input_type -> openpak.account.v1.UnlinkLinkRequest
	19, // 16: openpak.account.v1.Links.GetLinkBySubject:input_type -> openpak.account.v1.GetLinkBySubjectRequest
	20, // 17: openpak.account.v1.Links.GetActiveLinkByAccount:input_type -> openpak.account.v1.GetActiveLinkByAccountRequest
	4,  // 18: openpak.account.v1.Identity.VerifyPassword:output_type -> openpak.account.v1.VerifyPasswordResponse
	4,  // 19: openpak.account.v1.Identity.VerifyPasswordByID:output_type -> openpak.account.v1.VerifyPasswordResponse
	8,  // 20: openpak.account.v1.Identity.SetAdapterCredential:output_type -> openpak.account.v1.SetAdapterCredentialResponse
	10, // 21: openpak.account.v1.Identity.RequestAccountDeletion:output_type -> openpak.account.v1.RequestAccountDeletionResponse
	12, // 22: openpak.account.v1.Identity.VerifyAdapterCredential:output_type -> openpak.account.v1.VerifyAdapterCredentialResponse
	6,  // 23: openpak.account.v1.Identity.GetAccount:output_type -> openpak.account.v1.GetAccountResponse
	14, // 24: openpak.account.v1.Links.ReserveLink:output_type -> openpak.account.v1.ReserveLinkResponse
	16, // 25: openpak.account.v1.Links.ActivateLink:output_type -> openpak.account.v1.ActivateLinkResponse
	18, // 26: openpak.account.v1.Links.UnlinkLink:output_type -> openpak.account.v1.UnlinkLinkResponse
	21, // 27: openpak.account.v1.Links.GetLinkBySubject:output_type -> openpak.account.v1.GetLinkBySubjectResponse
	21, // 28: openpak.account.v1.Links.GetActiveLinkByAccount:output_type -> openpak.account.v1.GetLinkBySubjectResponse
	18, // [18:29] is the sub-list for method output_type
	7,  // [7:18] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_openpak_account_v1_account_proto_init() }
func file_openpak_account_v1_account_proto_init() {
	if File_openpak_account_v1_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openpak_account_v1_account_proto_rawDesc), len(file_openpak_account_v1_account_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_openpak_account_v1_account_proto_goTypes,
		DependencyIndexes: file_openpak_account_v1_account_proto_depIdxs,
		EnumInfos:         file_openpak_account_v1_account_proto_enumTypes,
		MessageInfos:      file_openpak_account_v1_account_proto_msgTypes,
	}.Build()
	File_openpak_account_v1_account_proto = out.File
	file_openpak_account_v1_account_proto_goTypes = nil
	file_openpak_account_v1_account_proto_depIdxs = nil
}
