// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: openpak/account/v1/account.proto

package accountv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Identity_VerifyPassword_FullMethodName          = "/openpak.account.v1.Identity/VerifyPassword"
	Identity_VerifyPasswordByID_FullMethodName      = "/openpak.account.v1.Identity/VerifyPasswordByID"
	Identity_SetAdapterCredential_FullMethodName    = "/openpak.account.v1.Identity/SetAdapterCredential"
	Identity_RequestAccountDeletion_FullMethodName  = "/openpak.account.v1.Identity/RequestAccountDeletion"
	Identity_VerifyAdapterCredential_FullMethodName = "/openpak.account.v1.Identity/VerifyAdapterCredential"
	Identity_GetAccount_FullMethodName              = "/openpak.account.v1.Identity/GetAccount"
)

// IdentityClient is the client API for Identity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Internal identity contract: narrowly scoped verification and status.
// Never exposes password hashes or recovery credentials.
type IdentityClient interface {
	// Verify an account's email+password. Returns a short-lived result bound to
	// the caller's namespace and purpose; never an unrestricted session.
	VerifyPassword(ctx context.Context, in *VerifyPasswordRequest, opts ...grpc.CallOption) (*VerifyPasswordResponse, error)
	// Verify by account ID, for adapters that resolve namespace subjects to
	// core accounts themselves (console login uses adapter usernames, so the
	// adapter maps subject→account and calls this).
	VerifyPasswordByID(ctx context.Context, in *VerifyPasswordByIDRequest, opts ...grpc.CallOption) (*VerifyPasswordResponse, error)
	// Store an adapter-domain credential (e.g. a console's transformed
	// password hash). Separate domain from web passwords (FR-1/FR-3).
	SetAdapterCredential(ctx context.Context, in *SetAdapterCredentialRequest, opts ...grpc.CallOption) (*SetAdapterCredentialResponse, error)
	// Start account deletion (FR-8): disables access immediately, emits
	// account_delete_started; full cleanup orchestration lands in M3/M4.
	RequestAccountDeletion(ctx context.Context, in *RequestAccountDeletionRequest, opts ...grpc.CallOption) (*RequestAccountDeletionResponse, error)
	// Verify an adapter-domain credential. Never yields a web session.
	VerifyAdapterCredential(ctx context.Context, in *VerifyAdapterCredentialRequest, opts ...grpc.CallOption) (*VerifyAdapterCredentialResponse, error)
	// Resolve an account by ID for status and minimal profile projection.
	GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error)
}

type identityClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityClient(cc grpc.ClientConnInterface) IdentityClient {
	return &identityClient{cc}
}

func (c *identityClient) VerifyPassword(ctx context.Context, in *VerifyPasswordRequest, opts ...grpc.CallOption) (*VerifyPasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyPasswordResponse)
	err := c.cc.Invoke(ctx, Identity_VerifyPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) VerifyPasswordByID(ctx context.Context, in *VerifyPasswordByIDRequest, opts ...grpc.CallOption) (*VerifyPasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyPasswordResponse)
	err := c.cc.Invoke(ctx, Identity_VerifyPasswordByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) SetAdapterCredential(ctx context.Context, in *SetAdapterCredentialRequest, opts ...grpc.CallOption) (*SetAdapterCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAdapterCredentialResponse)
	err := c.cc.Invoke(ctx, Identity_SetAdapterCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) RequestAccountDeletion(ctx context.Context, in *RequestAccountDeletionRequest, opts ...grpc.CallOption) (*RequestAccountDeletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestAccountDeletionResponse)
	err := c.cc.Invoke(ctx, Identity_RequestAccountDeletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) VerifyAdapterCredential(ctx context.Context, in *VerifyAdapterCredentialRequest, opts ...grpc.CallOption) (*VerifyAdapterCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyAdapterCredentialResponse)
	err := c.cc.Invoke(ctx, Identity_VerifyAdapterCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountResponse)
	err := c.cc.Invoke(ctx, Identity_GetAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServer is the server API for Identity service.
// All implementations must embed UnimplementedIdentityServer
// for forward compatibility.
//
// Internal identity contract: narrowly scoped verification and status.
// Never exposes password hashes or recovery credentials.
type IdentityServer interface {
	// Verify an account's email+password. Returns a short-lived result bound to
	// the caller's namespace and purpose; never an unrestricted session.
	VerifyPassword(context.Context, *VerifyPasswordRequest) (*VerifyPasswordResponse, error)
	// Verify by account ID, for adapters that resolve namespace subjects to
	// core accounts themselves (console login uses adapter usernames, so the
	// adapter maps subject→account and calls this).
	VerifyPasswordByID(context.Context, *VerifyPasswordByIDRequest) (*VerifyPasswordResponse, error)
	// Store an adapter-domain credential (e.g. a console's transformed
	// password hash). Separate domain from web passwords (FR-1/FR-3).
	SetAdapterCredential(context.Context, *SetAdapterCredentialRequest) (*SetAdapterCredentialResponse, error)
	// Start account deletion (FR-8): disables access immediately, emits
	// account_delete_started; full cleanup orchestration lands in M3/M4.
	RequestAccountDeletion(context.Context, *RequestAccountDeletionRequest) (*RequestAccountDeletionResponse, error)
	// Verify an adapter-domain credential. Never yields a web session.
	VerifyAdapterCredential(context.Context, *VerifyAdapterCredentialRequest) (*VerifyAdapterCredentialResponse, error)
	// Resolve an account by ID for status and minimal profile projection.
	GetAccount(context.Context, *GetAccountRequest) (*GetAccountResponse, error)
	mustEmbedUnimplementedIdentityServer()
}

// UnimplementedIdentityServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityServer struct{}

func (UnimplementedIdentityServer) VerifyPassword(context.Context, *VerifyPasswordRequest) (*VerifyPasswordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyPassword not implemented")
}
func (UnimplementedIdentityServer) VerifyPasswordByID(context.Context, *VerifyPasswordByIDRequest) (*VerifyPasswordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyPasswordByID not implemented")
}
func (UnimplementedIdentityServer) SetAdapterCredential(context.Context, *SetAdapterCredentialRequest) (*SetAdapterCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAdapterCredential not implemented")
}
func (UnimplementedIdentityServer) RequestAccountDeletion(context.Context, *RequestAccountDeletionRequest) (*RequestAccountDeletionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestAccountDeletion not implemented")
}
func (UnimplementedIdentityServer) VerifyAdapterCredential(context.Context, *VerifyAdapterCredentialRequest) (*VerifyAdapterCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyAdapterCredential not implemented")
}
func (UnimplementedIdentityServer) GetAccount(context.Context, *GetAccountRequest) (*GetAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccount not implemented")
}
func (UnimplementedIdentityServer) mustEmbedUnimplementedIdentityServer() {}
func (UnimplementedIdentityServer) testEmbeddedByValue()                  {}

// UnsafeIdentityServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityServer will
// result in compilation errors.
type UnsafeIdentityServer interface {
	mustEmbedUnimplementedIdentityServer()
}

func RegisterIdentityServer(s grpc.ServiceRegistrar, srv IdentityServer) {
	// If the following call panics, it indicates UnimplementedIdentityServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Identity_ServiceDesc, srv)
}

func _Identity_VerifyPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).VerifyPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Identity_VerifyPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).VerifyPassword(ctx, req.(*VerifyPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_VerifyPasswordByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPasswordByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).VerifyPasswordByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Identity_VerifyPasswordByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).VerifyPasswordByID(ctx, req.(*VerifyPasswordByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_SetAdapterCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAdapterCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).SetAdapterCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Identity_SetAdapterCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).SetAdapterCredential(ctx, req.(*SetAdapterCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_RequestAccountDeletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAccountDeletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).RequestAccountDeletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Identity_RequestAccountDeletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).RequestAccountDeletion(ctx, req.(*RequestAccountDeletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_VerifyAdapterCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyAdapterCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).VerifyAdapterCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Identity_VerifyAdapterCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).VerifyAdapterCredential(ctx, req.(*VerifyAdapterCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Identity_GetAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).GetAccount(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Identity_ServiceDesc is the grpc.ServiceDesc for Identity service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Identity_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openpak.account.v1.Identity",
	HandlerType: (*IdentityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyPassword",
			Handler:    _Identity_VerifyPassword_Handler,
		},
		{
			MethodName: "VerifyPasswordByID",
			Handler:    _Identity_VerifyPasswordByID_Handler,
		},
		{
			MethodName: "SetAdapterCredential",
			Handler:    _Identity_SetAdapterCredential_Handler,
		},
		{
			MethodName: "RequestAccountDeletion",
			Handler:    _Identity_RequestAccountDeletion_Handler,
		},
		{
			MethodName: "VerifyAdapterCredential",
			Handler:    _Identity_VerifyAdapterCredential_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _Identity_GetAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "openpak/account/v1/account.proto",
}

const (
	Links_ReserveLink_FullMethodName            = "/openpak.account.v1.Links/ReserveLink"
	Links_ActivateLink_FullMethodName           = "/openpak.account.v1.Links/ActivateLink"
	Links_UnlinkLink_FullMethodName             = "/openpak.account.v1.Links/UnlinkLink"
	Links_GetLinkBySubject_FullMethodName       = "/openpak.account.v1.Links/GetLinkBySubject"
	Links_GetActiveLinkByAccount_FullMethodName = "/openpak.account.v1.Links/GetActiveLinkByAccount"
)

// LinksClient is the client API for Links service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Generic, console-neutral adapter links. The core stores the adapter
// namespace and an opaque subject ID; it never interprets their contents.
type LinksClient interface {
	// Reserve a subject for an account (state: pending). Idempotent per
	// (namespace, subject_id); rejects conflicting account claims.
	ReserveLink(ctx context.Context, in *ReserveLinkRequest, opts ...grpc.CallOption) (*ReserveLinkResponse, error)
	// Activate a pending reservation once the adapter has proven ownership
	// (state: active). Fails if the reservation is not pending.
	ActivateLink(ctx context.Context, in *ActivateLinkRequest, opts ...grpc.CallOption) (*ActivateLinkResponse, error)
	// Unlink (state: revoking, then revoked). Does not delete the account.
	UnlinkLink(ctx context.Context, in *UnlinkLinkRequest, opts ...grpc.CallOption) (*UnlinkLinkResponse, error)
	// Look up the active link for an adapter subject.
	GetLinkBySubject(ctx context.Context, in *GetLinkBySubjectRequest, opts ...grpc.CallOption) (*GetLinkBySubjectResponse, error)
	// Resolve the active link for an account in one adapter namespace, so
	// adapter retries never mint a second subject (PRD SW-01). NotFound when
	// the account has no active link in that namespace.
	GetActiveLinkByAccount(ctx context.Context, in *GetActiveLinkByAccountRequest, opts ...grpc.CallOption) (*GetLinkBySubjectResponse, error)
}

type linksClient struct {
	cc grpc.ClientConnInterface
}

func NewLinksClient(cc grpc.ClientConnInterface) LinksClient {
	return &linksClient{cc}
}

func (c *linksClient) ReserveLink(ctx context.Context, in *ReserveLinkRequest, opts ...grpc.CallOption) (*ReserveLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveLinkResponse)
	err := c.cc.Invoke(ctx, Links_ReserveLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linksClient) ActivateLink(ctx context.Context, in *ActivateLinkRequest, opts ...grpc.CallOption) (*ActivateLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateLinkResponse)
	err := c.cc.Invoke(ctx, Links_ActivateLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linksClient) UnlinkLink(ctx context.Context, in *UnlinkLinkRequest, opts ...grpc.CallOption) (*UnlinkLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlinkLinkResponse)
	err := c.cc.Invoke(ctx, Links_UnlinkLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linksClient) GetLinkBySubject(ctx context.Context, in *GetLinkBySubjectRequest, opts ...grpc.CallOption) (*GetLinkBySubjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLinkBySubjectResponse)
	err := c.cc.Invoke(ctx, Links_GetLinkBySubject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linksClient) GetActiveLinkByAccount(ctx context.Context, in *GetActiveLinkByAccountRequest, opts ...grpc.CallOption) (*GetLinkBySubjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLinkBySubjectResponse)
	err := c.cc.Invoke(ctx, Links_GetActiveLinkByAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinksServer is the server API for Links service.
// All implementations must embed UnimplementedLinksServer
// for forward compatibility.
//
// Generic, console-neutral adapter links. The core stores the adapter
// namespace and an opaque subject ID; it never interprets their contents.
type LinksServer interface {
	// Reserve a subject for an account (state: pending). Idempotent per
	// (namespace, subject_id); rejects conflicting account claims.
	ReserveLink(context.Context, *ReserveLinkRequest) (*ReserveLinkResponse, error)
	// Activate a pending reservation once the adapter has proven ownership
	// (state: active). Fails if the reservation is not pending.
	ActivateLink(context.Context, *ActivateLinkRequest) (*ActivateLinkResponse, error)
	// Unlink (state: revoking, then revoked). Does not delete the account.
	UnlinkLink(context.Context, *UnlinkLinkRequest) (*UnlinkLinkResponse, error)
	// Look up the active link for an adapter subject.
	GetLinkBySubject(context.Context, *GetLinkBySubjectRequest) (*GetLinkBySubjectResponse, error)
	// Resolve the active link for an account in one adapter namespace, so
	// adapter retries never mint a second subject (PRD SW-01). NotFound when
	// the account has no active link in that namespace.
	GetActiveLinkByAccount(context.Context, *GetActiveLinkByAccountRequest) (*GetLinkBySubjectResponse, error)
	mustEmbedUnimplementedLinksServer()
}

// UnimplementedLinksServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLinksServer struct{}

func (UnimplementedLinksServer) ReserveLink(context.Context, *ReserveLinkRequest) (*ReserveLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveLink not implemented")
}
func (UnimplementedLinksServer) ActivateLink(context.Context, *ActivateLinkRequest) (*ActivateLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateLink not implemented")
}
func (UnimplementedLinksServer) UnlinkLink(context.Context, *UnlinkLinkRequest) (*UnlinkLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlinkLink not implemented")
}
func (UnimplementedLinksServer) GetLinkBySubject(context.Context, *GetLinkBySubjectRequest) (*GetLinkBySubjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLinkBySubject not implemented")
}
func (UnimplementedLinksServer) GetActiveLinkByAccount(context.Context, *GetActiveLinkByAccountRequest) (*GetLinkBySubjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveLinkByAccount not implemented")
}
func (UnimplementedLinksServer) mustEmbedUnimplementedLinksServer() {}
func (UnimplementedLinksServer) testEmbeddedByValue()               {}

// UnsafeLinksServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LinksServer will
// result in compilation errors.
type UnsafeLinksServer interface {
	mustEmbedUnimplementedLinksServer()
}

func RegisterLinksServer(s grpc.ServiceRegistrar, srv LinksServer) {
	// If the following call panics, it indicates UnimplementedLinksServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Links_ServiceDesc, srv)
}

func _Links_ReserveLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinksServer).ReserveLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Links_ReserveLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinksServer).ReserveLink(ctx, req.(*ReserveLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Links_ActivateLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinksServer).ActivateLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Links_ActivateLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinksServer).ActivateLink(ctx, req.(*ActivateLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Links_UnlinkLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlinkLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinksServer).UnlinkLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Links_UnlinkLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinksServer).UnlinkLink(ctx, req.(*UnlinkLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Links_GetLinkBySubject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLinkBySubjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinksServer).GetLinkBySubject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Links_GetLinkBySubject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinksServer).GetLinkBySubject(ctx, req.(*GetLinkBySubjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Links_GetActiveLinkByAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveLinkByAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinksServer).GetActiveLinkByAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Links_GetActiveLinkByAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinksServer).GetActiveLinkByAccount(ctx, req.(*GetActiveLinkByAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Links_ServiceDesc is the grpc.ServiceDesc for Links service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Links_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openpak.account.v1.Links",
	HandlerType: (*LinksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReserveLink",
			Handler:    _Links_ReserveLink_Handler,
		},
		{
			MethodName: "ActivateLink",
			Handler:    _Links_ActivateLink_Handler,
		},
		{
			MethodName: "UnlinkLink",
			Handler:    _Links_UnlinkLink_Handler,
		},
		{
			MethodName: "GetLinkBySubject",
			Handler:    _Links_GetLinkBySubject_Handler,
		},
		{
			MethodName: "GetActiveLinkByAccount",
			Handler:    _Links_GetActiveLinkByAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "openpak/account/v1/account.proto",
}
