// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: openpak/account/v1/federation.proto

package accountv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Federation_CreateNode_FullMethodName      = "/openpak.account.v1.Federation/CreateNode"
	Federation_Announce_FullMethodName        = "/openpak.account.v1.Federation/Announce"
	Federation_ListNodes_FullMethodName       = "/openpak.account.v1.Federation/ListNodes"
	Federation_ListAllNodes_FullMethodName    = "/openpak.account.v1.Federation/ListAllNodes"
	Federation_SetNodeApproved_FullMethodName = "/openpak.account.v1.Federation/SetNodeApproved"
)

// FederationClient is the client API for Federation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Region nodes. A node is a relay tier (Photon GameServer, NPLN relay, TURN)
// that announces its addresses; the matchmaking servers at home hand those
// addresses out per room, so a joiner lands wherever the host's room lives.
// Accounts, friends and matchmaking never leave home.
type FederationClient interface {
	// Called by the website on behalf of an operator. Returns the node's key
	// exactly once; the core keeps only its hash.
	CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*CreateNodeResponse, error)
	// Called by a node with its own key, about once a minute. Replaces the
	// node's advertised services and marks it seen.
	Announce(ctx context.Context, in *AnnounceRequest, opts ...grpc.CallOption) (*AnnounceResponse, error)
	// Approved nodes seen within the last few minutes. What the matchmaking
	// servers and the status page pick from.
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	// Every node, approved or not, seen or not: the admin view.
	ListAllNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	SetNodeApproved(ctx context.Context, in *SetNodeApprovedRequest, opts ...grpc.CallOption) (*SetNodeApprovedResponse, error)
}

type federationClient struct {
	cc grpc.ClientConnInterface
}

func NewFederationClient(cc grpc.ClientConnInterface) FederationClient {
	return &federationClient{cc}
}

func (c *federationClient) CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*CreateNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNodeResponse)
	err := c.cc.Invoke(ctx, Federation_CreateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationClient) Announce(ctx context.Context, in *AnnounceRequest, opts ...grpc.CallOption) (*AnnounceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnnounceResponse)
	err := c.cc.Invoke(ctx, Federation_Announce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, Federation_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationClient) ListAllNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, Federation_ListAllNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationClient) SetNodeApproved(ctx context.Context, in *SetNodeApprovedRequest, opts ...grpc.CallOption) (*SetNodeApprovedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetNodeApprovedResponse)
	err := c.cc.Invoke(ctx, Federation_SetNodeApproved_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FederationServer is the server API for Federation service.
// All implementations must embed UnimplementedFederationServer
// for forward compatibility.
//
// Region nodes. A node is a relay tier (Photon GameServer, NPLN relay, TURN)
// that announces its addresses; the matchmaking servers at home hand those
// addresses out per room, so a joiner lands wherever the host's room lives.
// Accounts, friends and matchmaking never leave home.
type FederationServer interface {
	// Called by the website on behalf of an operator. Returns the node's key
	// exactly once; the core keeps only its hash.
	CreateNode(context.Context, *CreateNodeRequest) (*CreateNodeResponse, error)
	// Called by a node with its own key, about once a minute. Replaces the
	// node's advertised services and marks it seen.
	Announce(context.Context, *AnnounceRequest) (*AnnounceResponse, error)
	// Approved nodes seen within the last few minutes. What the matchmaking
	// servers and the status page pick from.
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	// Every node, approved or not, seen or not: the admin view.
	ListAllNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	SetNodeApproved(context.Context, *SetNodeApprovedRequest) (*SetNodeApprovedResponse, error)
	mustEmbedUnimplementedFederationServer()
}

// UnimplementedFederationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFederationServer struct{}

func (UnimplementedFederationServer) CreateNode(context.Context, *CreateNodeRequest) (*CreateNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNode not implemented")
}
func (UnimplementedFederationServer) Announce(context.Context, *AnnounceRequest) (*AnnounceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Announce not implemented")
}
func (UnimplementedFederationServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedFederationServer) ListAllNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAllNodes not implemented")
}
func (UnimplementedFederationServer) SetNodeApproved(context.Context, *SetNodeApprovedRequest) (*SetNodeApprovedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetNodeApproved not implemented")
}
func (UnimplementedFederationServer) mustEmbedUnimplementedFederationServer() {}
func (UnimplementedFederationServer) testEmbeddedByValue()                    {}

// UnsafeFederationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FederationServer will
// result in compilation errors.
type UnsafeFederationServer interface {
	mustEmbedUnimplementedFederationServer()
}

func RegisterFederationServer(s grpc.ServiceRegistrar, srv FederationServer) {
	// If the following call panics, it indicates UnimplementedFederationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Federation_ServiceDesc, srv)
}

func _Federation_CreateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationServer).CreateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Federation_CreateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationServer).CreateNode(ctx, req.(*CreateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Federation_Announce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnnounceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationServer).Announce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Federation_Announce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationServer).Announce(ctx, req.(*AnnounceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Federation_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Federation_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Federation_ListAllNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationServer).ListAllNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Federation_ListAllNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationServer).ListAllNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Federation_SetNodeApproved_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNodeApprovedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationServer).SetNodeApproved(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Federation_SetNodeApproved_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationServer).SetNodeApproved(ctx, req.(*SetNodeApprovedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Federation_ServiceDesc is the grpc.ServiceDesc for Federation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Federation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openpak.account.v1.Federation",
	HandlerType: (*FederationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNode",
			Handler:    _Federation_CreateNode_Handler,
		},
		{
			MethodName: "Announce",
			Handler:    _Federation_Announce_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _Federation_ListNodes_Handler,
		},
		{
			MethodName: "ListAllNodes",
			Handler:    _Federation_ListAllNodes_Handler,
		},
		{
			MethodName: "SetNodeApproved",
			Handler:    _Federation_SetNodeApproved_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "openpak/account/v1/federation.proto",
}
