// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: openpak/account/v1/federation.proto

package accountv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // slug: [a-z0-9-], 2..32
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"` // ISO 3166-1 alpha-2
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNodeRequest) Reset() {
	*x = CreateNodeRequest{}
	mi := &file_openpak_account_v1_federation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeRequest) ProtoMessage() {}

func (x *CreateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_federation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeRequest.ProtoReflect.Descriptor instead.
func (*CreateNodeRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_federation_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CreateNodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNodeRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type CreateNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"` // shown once
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNodeResponse) Reset() {
	*x = CreateNodeResponse{}
	mi := &file_openpak_account_v1_federation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeResponse) ProtoMessage() {}

func (x *CreateNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_federation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeResponse.ProtoReflect.Descriptor instead.
func (*CreateNodeResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_federation_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNodeResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CreateNodeResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type AnnounceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      map[string]string      `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // service -> host:port
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnounceRequest) Reset() {
	*x = AnnounceRequest{}
	mi := &file_openpak_account_v1_federation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnounceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnounceRequest) ProtoMessage() {}

func (x *AnnounceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_federation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnounceRequest.ProtoReflect.Descriptor instead.
func (*AnnounceRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_federation_proto_rawDescGZIP(), []int{2}
}

func (x *AnnounceRequest) GetServices() map[string]string {
	if x != nil {
		return x.Services
	}
	return nil
}

type AnnounceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Approved      bool                   `protobuf:"varint,2,opt,name=approved,proto3" json:"approved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnounceResponse) Reset() {
	*x = AnnounceResponse{}
	mi := &file_openpak_account_v1_federation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnounceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnounceResponse) ProtoMessage() {}

func (x *AnnounceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_federation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnounceResponse.ProtoReflect.Descriptor instead.
func (*AnnounceResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_federation_proto_rawDescGZIP(), []int{3}
}

func (x *AnnounceResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AnnounceResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_openpak_account_v1_federation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_federation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_federation_proto_rawDescGZIP(), []int{4}
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_openpak_account_v1_federation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_federation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_federation_proto_rawDescGZIP(), []int{5}
}

func (x *ListNodesResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Services      map[string]string      `protobuf:"bytes,4,rep,name=services,proto3" json:"services,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LastSeenUnix  int64                  `protobuf:"varint,5,opt,name=last_seen_unix,json=lastSeenUnix,proto3" json:"last_seen_unix,omitempty"` // 0 = never
	Approved      bool                   `protobuf:"varint,6,opt,name=approved,proto3" json:"approved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_openpak_account_v1_federation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_federation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_federation_proto_rawDescGZIP(), []int{6}
}

func (x *Node) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Node) GetServices() map[string]string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *Node) GetLastSeenUnix() int64 {
	if x != nil {
		return x.LastSeenUnix
	}
	return 0
}

func (x *Node) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

type SetNodeApprovedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Approved      bool                   `protobuf:"varint,2,opt,name=approved,proto3" json:"approved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNodeApprovedRequest) Reset() {
	*x = SetNodeApprovedRequest{}
	mi := &file_openpak_account_v1_federation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNodeApprovedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNodeApprovedRequest) ProtoMessage() {}

func (x *SetNodeApprovedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_federation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNodeApprovedRequest.ProtoReflect.Descriptor instead.
func (*SetNodeApprovedRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_federation_proto_rawDescGZIP(), []int{7}
}

func (x *SetNodeApprovedRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SetNodeApprovedRequest) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

type SetNodeApprovedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNodeApprovedResponse) Reset() {
	*x = SetNodeApprovedResponse{}
	mi := &file_openpak_account_v1_federation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNodeApprovedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNodeApprovedResponse) ProtoMessage() {}

func (x *SetNodeApprovedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_federation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNodeApprovedResponse.ProtoReflect.Descriptor instead.
func (*SetNodeApprovedResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_federation_proto_rawDescGZIP(), []int{8}
}

var File_openpak_account_v1_federation_proto protoreflect.FileDescriptor

const file_openpak_account_v1_federation_proto_rawDesc = "" +
	"\n" +
	"#openpak/account/v1/federation.proto\x12\x12openpak.account.v1\"Z\n" +
	"\x11CreateNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\"?\n" +
	"\x12CreateNodeResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\x9d\x01\n" +
	"\x0fAnnounceRequest\x12M\n" +
	"\bservices\x18\x01 \x03(\v21.openpak.account.v1.AnnounceRequest.ServicesEntryR\bservices\x1a;\n" +
	"\rServicesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\x10AnnounceResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bapproved\x18\x02 \x01(\bR\bapproved\"\x12\n" +
	"\x10ListNodesRequest\"C\n" +
	"\x11ListNodesResponse\x12.\n" +
	"\x05nodes\x18\x01 \x03(\v2\x18.openpak.account.v1.NodeR\x05nodes\"\x90\x02\n" +
	"\x04Node\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12B\n" +
	"\bservices\x18\x04 \x03(\v2&.openpak.account.v1.Node.ServicesEntryR\bservices\x12$\n" +
	"\x0elast_seen_unix\x18\x05 \x01(\x03R\flastSeenUnix\x12\x1a\n" +
	"\bapproved\x18\x06 \x01(\bR\bapproved\x1a;\n" +
	"\rServicesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\x16SetNodeApprovedRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bapproved\x18\x02 \x01(\bR\bapproved\"\x19\n" +
	"\x17SetNodeApprovedResponse2\xe3\x03\n" +
	"\n" +
	"Federation\x12[\n" +
	"\n" +
	"CreateNode\x12%.openpak.account.v1.CreateNodeRequest\x1a&.openpak.account.v1.CreateNodeResponse\x12U\n" +
	"\bAnnounce\x12#.openpak.account.v1.AnnounceRequest\x1a$.openpak.account.v1.AnnounceResponse\x12X\n" +
	"\tListNodes\x12$.openpak.account.v1.ListNodesRequest\x1a%.openpak.account.v1.ListNodesResponse\x12[\n" +
	"\fListAllNodes\x12$.openpak.account.v1.ListNodesRequest\x1a%.openpak.account.v1.ListNodesResponse\x12j\n" +
	"\x0fSetNodeApproved\x12*.openpak.account.v1.SetNodeApprovedRequest\x1a+.openpak.account.v1.SetNodeApprovedResponseB4Z2openpak/account/proto/openpak/account/v1;accountv1b\x06proto3"

var (
	file_openpak_account_v1_federation_proto_rawDescOnce sync.Once
	file_openpak_account_v1_federation_proto_rawDescData []byte
)

func file_openpak_account_v1_federation_proto_rawDescGZIP() []byte {
	file_openpak_account_v1_federation_proto_rawDescOnce.Do(func() {
		file_openpak_account_v1_federation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openpak_account_v1_federation_proto_rawDesc), len(file_openpak_account_v1_federation_proto_rawDesc)))
	})
	return file_openpak_account_v1_federation_proto_rawDescData
}

var file_openpak_account_v1_federation_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_openpak_account_v1_federation_proto_goTypes = []any{
	(*CreateNodeRequest)(nil),       // 0: openpak.account.v1.CreateNodeRequest
	(*CreateNodeResponse)(nil),      // 1: openpak.account.v1.CreateNodeResponse
	(*AnnounceRequest)(nil),         // 2: openpak.account.v1.AnnounceRequest
	(*AnnounceResponse)(nil),        // 3: openpak.account.v1.AnnounceResponse
	(*ListNodesRequest)(nil),        // 4: openpak.account.v1.ListNodesRequest
	(*ListNodesResponse)(nil),       // 5: openpak.account.v1.ListNodesResponse
	(*Node)(nil),                    // 6: openpak.account.v1.Node
	(*SetNodeApprovedRequest)(nil),  // 7: openpak.account.v1.SetNodeApprovedRequest
	(*SetNodeApprovedResponse)(nil), // 8: openpak.account.v1.SetNodeApprovedResponse
	nil,                             // 9: openpak.account.v1.AnnounceRequest.ServicesEntry
	nil,                             // 10: openpak.account.v1.Node.ServicesEntry
}
var file_openpak_account_v1_federation_proto_depIdxs = []int32{
	9,  // 0: openpak.account.v1.AnnounceRequest.services:type_name -> openpak.account.v1.AnnounceRequest.ServicesEntry
	6,  // 1: openpak.account.v1.ListNodesResponse.nodes:type_name -> openpak.account.v1.Node
	10, // 2: openpak.account.v1.Node.services:type_name -> openpak.account.v1.Node.ServicesEntry
	0,  // 3: openpak.account.v1.Federation.CreateNode:input_type -> openpak.account.v1.CreateNodeRequest
	2,  // 4: openpak.account.v1.Federation.Announce:input_type -> openpak.account.v1.AnnounceRequest
	4,  // 5: openpak.account.v1.Federation.ListNodes:input_type -> openpak.account.v1.ListNodesRequest
	4,  // 6: openpak.account.v1.Federation.ListAllNodes:input_type -> openpak.account.v1.ListNodesRequest
	7,  // 7: openpak.account.v1.Federation.SetNodeApproved:input_type -> openpak.account.v1.SetNodeApprovedRequest
	1,  // 8: openpak.account.v1.Federation.CreateNode:output_type -> openpak.account.v1.CreateNodeResponse
	3,  // 9: openpak.account.v1.Federation.Announce:output_type -> openpak.account.v1.AnnounceResponse
	5,  // 10: openpak.account.v1.Federation.ListNodes:output_type -> openpak.account.v1.ListNodesResponse
	5,  // 11: openpak.account.v1.Federation.ListAllNodes:output_type -> openpak.account.v1.ListNodesResponse
	8,  // 12: openpak.account.v1.Federation.SetNodeApproved:output_type -> openpak.account.v1.SetNodeApprovedResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_openpak_account_v1_federation_proto_init() }
func file_openpak_account_v1_federation_proto_init() {
	if File_openpak_account_v1_federation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openpak_account_v1_federation_proto_rawDesc), len(file_openpak_account_v1_federation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_openpak_account_v1_federation_proto_goTypes,
		DependencyIndexes: file_openpak_account_v1_federation_proto_depIdxs,
		MessageInfos:      file_openpak_account_v1_federation_proto_msgTypes,
	}.Build()
	File_openpak_account_v1_federation_proto = out.File
	file_openpak_account_v1_federation_proto_goTypes = nil
	file_openpak_account_v1_federation_proto_depIdxs = nil
}
