// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: openpak/account/v1/registration.proto

package accountv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterAccountRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CallerNamespace string                 `protobuf:"bytes,1,opt,name=caller_namespace,json=callerNamespace,proto3" json:"caller_namespace,omitempty"` // adapter namespace
	Purpose         string                 `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`                                        // e.g. "console_registration"
	Email           string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password        string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	DisplayName     string                 `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Console-expressed locale, kept for the adapter's own records only.
	Country       string `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	Language      string `protobuf:"bytes,7,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAccountRequest) Reset() {
	*x = RegisterAccountRequest{}
	mi := &file_openpak_account_v1_registration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAccountRequest) ProtoMessage() {}

func (x *RegisterAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_registration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAccountRequest.ProtoReflect.Descriptor instead.
func (*RegisterAccountRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_registration_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterAccountRequest) GetCallerNamespace() string {
	if x != nil {
		return x.CallerNamespace
	}
	return ""
}

func (x *RegisterAccountRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *RegisterAccountRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterAccountRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterAccountRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *RegisterAccountRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *RegisterAccountRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type RegisterAccountResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AccountId string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Delivery of the verification email is the core's responsibility. The
	// token is returned only so tests/development can complete the flow; the
	// production core mails it and returns an empty string.
	VerificationToken string `protobuf:"bytes,2,opt,name=verification_token,json=verificationToken,proto3" json:"verification_token,omitempty"`
	EmailTaken        bool   `protobuf:"varint,3,opt,name=email_taken,json=emailTaken,proto3" json:"email_taken,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterAccountResponse) Reset() {
	*x = RegisterAccountResponse{}
	mi := &file_openpak_account_v1_registration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAccountResponse) ProtoMessage() {}

func (x *RegisterAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_registration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAccountResponse.ProtoReflect.Descriptor instead.
func (*RegisterAccountResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_registration_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterAccountResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *RegisterAccountResponse) GetVerificationToken() string {
	if x != nil {
		return x.VerificationToken
	}
	return ""
}

func (x *RegisterAccountResponse) GetEmailTaken() bool {
	if x != nil {
		return x.EmailTaken
	}
	return false
}

var File_openpak_account_v1_registration_proto protoreflect.FileDescriptor

const file_openpak_account_v1_registration_proto_rawDesc = "" +
	"\n" +
	"%openpak/account/v1/registration.proto\x12\x12openpak.account.v1\"\xe8\x01\n" +
	"\x16RegisterAccountRequest\x12)\n" +
	"\x10caller_namespace\x18\x01 \x01(\tR\x0fcallerNamespace\x12\x18\n" +
	"\apurpose\x18\x02 \x01(\tR\apurpose\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12!\n" +
	"\fdisplay_name\x18\x05 \x01(\tR\vdisplayName\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\x12\x1a\n" +
	"\blanguage\x18\a \x01(\tR\blanguage\"\x88\x01\n" +
	"\x17RegisterAccountResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12-\n" +
	"\x12verification_token\x18\x02 \x01(\tR\x11verificationToken\x12\x1f\n" +
	"\vemail_taken\x18\x03 \x01(\bR\n" +
	"emailTaken2z\n" +
	"\fRegistration\x12j\n" +
	"\x0fRegisterAccount\x12*.openpak.account.v1.RegisterAccountRequest\x1a+.openpak.account.v1.RegisterAccountResponseB4Z2openpak/account/proto/openpak/account/v1;accountv1b\x06proto3"

var (
	file_openpak_account_v1_registration_proto_rawDescOnce sync.Once
	file_openpak_account_v1_registration_proto_rawDescData []byte
)

func file_openpak_account_v1_registration_proto_rawDescGZIP() []byte {
	file_openpak_account_v1_registration_proto_rawDescOnce.Do(func() {
		file_openpak_account_v1_registration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openpak_account_v1_registration_proto_rawDesc), len(file_openpak_account_v1_registration_proto_rawDesc)))
	})
	return file_openpak_account_v1_registration_proto_rawDescData
}

var file_openpak_account_v1_registration_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_openpak_account_v1_registration_proto_goTypes = []any{
	(*RegisterAccountRequest)(nil),  // 0: openpak.account.v1.RegisterAccountRequest
	(*RegisterAccountResponse)(nil), // 1: openpak.account.v1.RegisterAccountResponse
}
var file_openpak_account_v1_registration_proto_depIdxs = []int32{
	0, // 0: openpak.account.v1.Registration.RegisterAccount:input_type -> openpak.account.v1.RegisterAccountRequest
	1, // 1: openpak.account.v1.Registration.RegisterAccount:output_type -> openpak.account.v1.RegisterAccountResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_openpak_account_v1_registration_proto_init() }
func file_openpak_account_v1_registration_proto_init() {
	if File_openpak_account_v1_registration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openpak_account_v1_registration_proto_rawDesc), len(file_openpak_account_v1_registration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_openpak_account_v1_registration_proto_goTypes,
		DependencyIndexes: file_openpak_account_v1_registration_proto_depIdxs,
		MessageInfos:      file_openpak_account_v1_registration_proto_msgTypes,
	}.Build()
	File_openpak_account_v1_registration_proto = out.File
	file_openpak_account_v1_registration_proto_goTypes = nil
	file_openpak_account_v1_registration_proto_depIdxs = nil
}
