// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: openpak/account/v1/sessions_invitations.proto

package accountv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sessions_RegisterSession_FullMethodName = "/openpak.account.v1.Sessions/RegisterSession"
	Sessions_Heartbeat_FullMethodName       = "/openpak.account.v1.Sessions/Heartbeat"
	Sessions_ExpireSession_FullMethodName   = "/openpak.account.v1.Sessions/ExpireSession"
	Sessions_ResolveSession_FullMethodName  = "/openpak.account.v1.Sessions/ResolveSession"
	Sessions_GetPresence_FullMethodName     = "/openpak.account.v1.Sessions/GetPresence"
	Sessions_GetPlayerCounts_FullMethodName = "/openpak.account.v1.Sessions/GetPlayerCounts"
)

// SessionsClient is the client API for Sessions service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Live-session registry and core-routed invitations (PRD SW-06/SW-07).
// Adapters register sessions with short leases; the core routes invitations
// to a live session for the target account and title. Leases and expiry are
// core-owned so stale-session cleanup has a shared clock.
type SessionsClient interface {
	// Register a live session. A server-side session_id is returned; the
	// lease (default 30 s) must be renewed by Heartbeat before expiry.
	RegisterSession(ctx context.Context, in *RegisterSessionRequest, opts ...grpc.CallOption) (*RegisterSessionResponse, error)
	// Renew the lease. Fails if the session expired or was expired.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Explicit teardown (clean disconnect, host exit).
	ExpireSession(ctx context.Context, in *ExpireSessionRequest, opts ...grpc.CallOption) (*ExpireSessionResponse, error)
	// Resolve the live session for an account and title, if any.
	ResolveSession(ctx context.Context, in *ResolveSessionRequest, opts ...grpc.CallOption) (*ResolveSessionResponse, error)
	// Presence for a set of accounts, derived from their live session leases:
	// who is online and in which title. A read for companion surfaces (a phone
	// showing a friends list); it registers nothing and renews nothing.
	GetPresence(ctx context.Context, in *GetPresenceRequest, opts ...grpc.CallOption) (*GetPresenceResponse, error)
	// How many people are playing, per title. Derived from the same live leases
	// as presence, so a status page and a friends list can never disagree about
	// who is online. Counts accounts, not sessions.
	GetPlayerCounts(ctx context.Context, in *GetPlayerCountsRequest, opts ...grpc.CallOption) (*GetPlayerCountsResponse, error)
}

type sessionsClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionsClient(cc grpc.ClientConnInterface) SessionsClient {
	return &sessionsClient{cc}
}

func (c *sessionsClient) RegisterSession(ctx context.Context, in *RegisterSessionRequest, opts ...grpc.CallOption) (*RegisterSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterSessionResponse)
	err := c.cc.Invoke(ctx, Sessions_RegisterSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, Sessions_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) ExpireSession(ctx context.Context, in *ExpireSessionRequest, opts ...grpc.CallOption) (*ExpireSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExpireSessionResponse)
	err := c.cc.Invoke(ctx, Sessions_ExpireSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) ResolveSession(ctx context.Context, in *ResolveSessionRequest, opts ...grpc.CallOption) (*ResolveSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveSessionResponse)
	err := c.cc.Invoke(ctx, Sessions_ResolveSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) GetPresence(ctx context.Context, in *GetPresenceRequest, opts ...grpc.CallOption) (*GetPresenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPresenceResponse)
	err := c.cc.Invoke(ctx, Sessions_GetPresence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) GetPlayerCounts(ctx context.Context, in *GetPlayerCountsRequest, opts ...grpc.CallOption) (*GetPlayerCountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlayerCountsResponse)
	err := c.cc.Invoke(ctx, Sessions_GetPlayerCounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionsServer is the server API for Sessions service.
// All implementations must embed UnimplementedSessionsServer
// for forward compatibility.
//
// Live-session registry and core-routed invitations (PRD SW-06/SW-07).
// Adapters register sessions with short leases; the core routes invitations
// to a live session for the target account and title. Leases and expiry are
// core-owned so stale-session cleanup has a shared clock.
type SessionsServer interface {
	// Register a live session. A server-side session_id is returned; the
	// lease (default 30 s) must be renewed by Heartbeat before expiry.
	RegisterSession(context.Context, *RegisterSessionRequest) (*RegisterSessionResponse, error)
	// Renew the lease. Fails if the session expired or was expired.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Explicit teardown (clean disconnect, host exit).
	ExpireSession(context.Context, *ExpireSessionRequest) (*ExpireSessionResponse, error)
	// Resolve the live session for an account and title, if any.
	ResolveSession(context.Context, *ResolveSessionRequest) (*ResolveSessionResponse, error)
	// Presence for a set of accounts, derived from their live session leases:
	// who is online and in which title. A read for companion surfaces (a phone
	// showing a friends list); it registers nothing and renews nothing.
	GetPresence(context.Context, *GetPresenceRequest) (*GetPresenceResponse, error)
	// How many people are playing, per title. Derived from the same live leases
	// as presence, so a status page and a friends list can never disagree about
	// who is online. Counts accounts, not sessions.
	GetPlayerCounts(context.Context, *GetPlayerCountsRequest) (*GetPlayerCountsResponse, error)
	mustEmbedUnimplementedSessionsServer()
}

// UnimplementedSessionsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionsServer struct{}

func (UnimplementedSessionsServer) RegisterSession(context.Context, *RegisterSessionRequest) (*RegisterSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterSession not implemented")
}
func (UnimplementedSessionsServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedSessionsServer) ExpireSession(context.Context, *ExpireSessionRequest) (*ExpireSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExpireSession not implemented")
}
func (UnimplementedSessionsServer) ResolveSession(context.Context, *ResolveSessionRequest) (*ResolveSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveSession not implemented")
}
func (UnimplementedSessionsServer) GetPresence(context.Context, *GetPresenceRequest) (*GetPresenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPresence not implemented")
}
func (UnimplementedSessionsServer) GetPlayerCounts(context.Context, *GetPlayerCountsRequest) (*GetPlayerCountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlayerCounts not implemented")
}
func (UnimplementedSessionsServer) mustEmbedUnimplementedSessionsServer() {}
func (UnimplementedSessionsServer) testEmbeddedByValue()                  {}

// UnsafeSessionsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionsServer will
// result in compilation errors.
type UnsafeSessionsServer interface {
	mustEmbedUnimplementedSessionsServer()
}

func RegisterSessionsServer(s grpc.ServiceRegistrar, srv SessionsServer) {
	// If the following call panics, it indicates UnimplementedSessionsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sessions_ServiceDesc, srv)
}

func _Sessions_RegisterSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).RegisterSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_RegisterSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).RegisterSession(ctx, req.(*RegisterSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_ExpireSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpireSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).ExpireSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_ExpireSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).ExpireSession(ctx, req.(*ExpireSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_ResolveSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).ResolveSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_ResolveSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).ResolveSession(ctx, req.(*ResolveSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_GetPresence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPresenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).GetPresence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_GetPresence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).GetPresence(ctx, req.(*GetPresenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_GetPlayerCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerCountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).GetPlayerCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_GetPlayerCounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).GetPlayerCounts(ctx, req.(*GetPlayerCountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sessions_ServiceDesc is the grpc.ServiceDesc for Sessions service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sessions_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openpak.account.v1.Sessions",
	HandlerType: (*SessionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterSession",
			Handler:    _Sessions_RegisterSession_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Sessions_Heartbeat_Handler,
		},
		{
			MethodName: "ExpireSession",
			Handler:    _Sessions_ExpireSession_Handler,
		},
		{
			MethodName: "ResolveSession",
			Handler:    _Sessions_ResolveSession_Handler,
		},
		{
			MethodName: "GetPresence",
			Handler:    _Sessions_GetPresence_Handler,
		},
		{
			MethodName: "GetPlayerCounts",
			Handler:    _Sessions_GetPlayerCounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "openpak/account/v1/sessions_invitations.proto",
}

const (
	Invitations_SendInvitation_FullMethodName   = "/openpak.account.v1.Invitations/SendInvitation"
	Invitations_PollInvitations_FullMethodName  = "/openpak.account.v1.Invitations/PollInvitations"
	Invitations_AckInvitations_FullMethodName   = "/openpak.account.v1.Invitations/AckInvitations"
	Invitations_ListInvitations_FullMethodName  = "/openpak.account.v1.Invitations/ListInvitations"
	Invitations_RejectInvitation_FullMethodName = "/openpak.account.v1.Invitations/RejectInvitation"
)

// InvitationsClient is the client API for Invitations service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InvitationsClient interface {
	// Deliver an invitation to a live session. The core enforces CheckInteraction
	// rules, stamps expiry and a nonce (replay rejection), requires a live
	// session for the target account + title, and binds the invitation to that
	// session (delivery fails if the session is replaced, expired, or removed;
	// blocks are re-checked at delivery time).
	SendInvitation(ctx context.Context, in *SendInvitationRequest, opts ...grpc.CallOption) (*SendInvitationResponse, error)
	// Poll pending invitations for an account on one adapter namespace.
	// Delivery is at-least-once: returned invitations stay pending for a
	// redelivery window (60 s) until acknowledged, so a lost response is
	// recovered by polling again. Expired or policy-invalid invitations are
	// reaped/rejected server-side before delivery.
	PollInvitations(ctx context.Context, in *PollInvitationsRequest, opts ...grpc.CallOption) (*PollInvitationsResponse, error)
	// Acknowledge received invitations (id + nonce pairs). Only pending
	// invitations matching namespace/account/nonce are marked delivered.
	AckInvitations(ctx context.Context, in *AckInvitationsRequest, opts ...grpc.CallOption) (*AckInvitationsResponse, error)
	// Read the pending invitations addressed to an account, across every
	// namespace, WITHOUT consuming them: no redelivery window is started and
	// nothing is marked delivered, so a companion app showing an inbox cannot
	// take an invitation away from the adapter that has to deliver it. The
	// summary carries no payload and no nonce; both belong to that adapter.
	ListInvitations(ctx context.Context, in *ListInvitationsRequest, opts ...grpc.CallOption) (*ListInvitationsResponse, error)
	// Reject an invitation on behalf of its recipient (the "decline" button).
	// Only the account it was addressed to can reject it, and only while it is
	// still pending.
	RejectInvitation(ctx context.Context, in *RejectInvitationRequest, opts ...grpc.CallOption) (*RejectInvitationResponse, error)
}

type invitationsClient struct {
	cc grpc.ClientConnInterface
}

func NewInvitationsClient(cc grpc.ClientConnInterface) InvitationsClient {
	return &invitationsClient{cc}
}

func (c *invitationsClient) SendInvitation(ctx context.Context, in *SendInvitationRequest, opts ...grpc.CallOption) (*SendInvitationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendInvitationResponse)
	err := c.cc.Invoke(ctx, Invitations_SendInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invitationsClient) PollInvitations(ctx context.Context, in *PollInvitationsRequest, opts ...grpc.CallOption) (*PollInvitationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollInvitationsResponse)
	err := c.cc.Invoke(ctx, Invitations_PollInvitations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invitationsClient) AckInvitations(ctx context.Context, in *AckInvitationsRequest, opts ...grpc.CallOption) (*AckInvitationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckInvitationsResponse)
	err := c.cc.Invoke(ctx, Invitations_AckInvitations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invitationsClient) ListInvitations(ctx context.Context, in *ListInvitationsRequest, opts ...grpc.CallOption) (*ListInvitationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInvitationsResponse)
	err := c.cc.Invoke(ctx, Invitations_ListInvitations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invitationsClient) RejectInvitation(ctx context.Context, in *RejectInvitationRequest, opts ...grpc.CallOption) (*RejectInvitationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectInvitationResponse)
	err := c.cc.Invoke(ctx, Invitations_RejectInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InvitationsServer is the server API for Invitations service.
// All implementations must embed UnimplementedInvitationsServer
// for forward compatibility.
type InvitationsServer interface {
	// Deliver an invitation to a live session. The core enforces CheckInteraction
	// rules, stamps expiry and a nonce (replay rejection), requires a live
	// session for the target account + title, and binds the invitation to that
	// session (delivery fails if the session is replaced, expired, or removed;
	// blocks are re-checked at delivery time).
	SendInvitation(context.Context, *SendInvitationRequest) (*SendInvitationResponse, error)
	// Poll pending invitations for an account on one adapter namespace.
	// Delivery is at-least-once: returned invitations stay pending for a
	// redelivery window (60 s) until acknowledged, so a lost response is
	// recovered by polling again. Expired or policy-invalid invitations are
	// reaped/rejected server-side before delivery.
	PollInvitations(context.Context, *PollInvitationsRequest) (*PollInvitationsResponse, error)
	// Acknowledge received invitations (id + nonce pairs). Only pending
	// invitations matching namespace/account/nonce are marked delivered.
	AckInvitations(context.Context, *AckInvitationsRequest) (*AckInvitationsResponse, error)
	// Read the pending invitations addressed to an account, across every
	// namespace, WITHOUT consuming them: no redelivery window is started and
	// nothing is marked delivered, so a companion app showing an inbox cannot
	// take an invitation away from the adapter that has to deliver it. The
	// summary carries no payload and no nonce; both belong to that adapter.
	ListInvitations(context.Context, *ListInvitationsRequest) (*ListInvitationsResponse, error)
	// Reject an invitation on behalf of its recipient (the "decline" button).
	// Only the account it was addressed to can reject it, and only while it is
	// still pending.
	RejectInvitation(context.Context, *RejectInvitationRequest) (*RejectInvitationResponse, error)
	mustEmbedUnimplementedInvitationsServer()
}

// UnimplementedInvitationsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInvitationsServer struct{}

func (UnimplementedInvitationsServer) SendInvitation(context.Context, *SendInvitationRequest) (*SendInvitationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendInvitation not implemented")
}
func (UnimplementedInvitationsServer) PollInvitations(context.Context, *PollInvitationsRequest) (*PollInvitationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PollInvitations not implemented")
}
func (UnimplementedInvitationsServer) AckInvitations(context.Context, *AckInvitationsRequest) (*AckInvitationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AckInvitations not implemented")
}
func (UnimplementedInvitationsServer) ListInvitations(context.Context, *ListInvitationsRequest) (*ListInvitationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInvitations not implemented")
}
func (UnimplementedInvitationsServer) RejectInvitation(context.Context, *RejectInvitationRequest) (*RejectInvitationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectInvitation not implemented")
}
func (UnimplementedInvitationsServer) mustEmbedUnimplementedInvitationsServer() {}
func (UnimplementedInvitationsServer) testEmbeddedByValue()                     {}

// UnsafeInvitationsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InvitationsServer will
// result in compilation errors.
type UnsafeInvitationsServer interface {
	mustEmbedUnimplementedInvitationsServer()
}

func RegisterInvitationsServer(s grpc.ServiceRegistrar, srv InvitationsServer) {
	// If the following call panics, it indicates UnimplementedInvitationsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Invitations_ServiceDesc, srv)
}

func _Invitations_SendInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvitationsServer).SendInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Invitations_SendInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvitationsServer).SendInvitation(ctx, req.(*SendInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Invitations_PollInvitations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollInvitationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvitationsServer).PollInvitations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Invitations_PollInvitations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvitationsServer).PollInvitations(ctx, req.(*PollInvitationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Invitations_AckInvitations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckInvitationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvitationsServer).AckInvitations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Invitations_AckInvitations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvitationsServer).AckInvitations(ctx, req.(*AckInvitationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Invitations_ListInvitations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInvitationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvitationsServer).ListInvitations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Invitations_ListInvitations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvitationsServer).ListInvitations(ctx, req.(*ListInvitationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Invitations_RejectInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvitationsServer).RejectInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Invitations_RejectInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvitationsServer).RejectInvitation(ctx, req.(*RejectInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Invitations_ServiceDesc is the grpc.ServiceDesc for Invitations service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Invitations_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openpak.account.v1.Invitations",
	HandlerType: (*InvitationsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendInvitation",
			Handler:    _Invitations_SendInvitation_Handler,
		},
		{
			MethodName: "PollInvitations",
			Handler:    _Invitations_PollInvitations_Handler,
		},
		{
			MethodName: "AckInvitations",
			Handler:    _Invitations_AckInvitations_Handler,
		},
		{
			MethodName: "ListInvitations",
			Handler:    _Invitations_ListInvitations_Handler,
		},
		{
			MethodName: "RejectInvitation",
			Handler:    _Invitations_RejectInvitation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "openpak/account/v1/sessions_invitations.proto",
}
