// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: openpak/account/v1/sessions_invitations.proto

package accountv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`                            // owning adapter namespace (e.g. "switch")
	TitleId       string                 `protobuf:"bytes,3,opt,name=title_id,json=titleId,proto3" json:"title_id,omitempty"`                 // adapter-scoped title/tenant routing metadata
	EndpointRef   string                 `protobuf:"bytes,4,opt,name=endpoint_ref,json=endpointRef,proto3" json:"endpoint_ref,omitempty"`     // opaque adapter-interpreted delivery handle
	LeaseSeconds  int32                  `protobuf:"varint,5,opt,name=lease_seconds,json=leaseSeconds,proto3" json:"lease_seconds,omitempty"` // optional; server default 30, cap 300
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterSessionRequest) Reset() {
	*x = RegisterSessionRequest{}
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSessionRequest) ProtoMessage() {}

func (x *RegisterSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSessionRequest.ProtoReflect.Descriptor instead.
func (*RegisterSessionRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_sessions_invitations_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterSessionRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *RegisterSessionRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RegisterSessionRequest) GetTitleId() string {
	if x != nil {
		return x.TitleId
	}
	return ""
}

func (x *RegisterSessionRequest) GetEndpointRef() string {
	if x != nil {
		return x.EndpointRef
	}
	return ""
}

func (x *RegisterSessionRequest) GetLeaseSeconds() int32 {
	if x != nil {
		return x.LeaseSeconds
	}
	return 0
}

type RegisterSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	LeaseSeconds  int32                  `protobuf:"varint,2,opt,name=lease_seconds,json=leaseSeconds,proto3" json:"lease_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterSessionResponse) Reset() {
	*x = RegisterSessionResponse{}
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSessionResponse) ProtoMessage() {}

func (x *RegisterSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSessionResponse.ProtoReflect.Descriptor instead.
func (*RegisterSessionResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_sessions_invitations_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegisterSessionResponse) GetLeaseSeconds() int32 {
	if x != nil {
		return x.LeaseSeconds
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_sessions_invitations_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseSeconds  int32                  `protobuf:"varint,1,opt,name=lease_seconds,json=leaseSeconds,proto3" json:"lease_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_sessions_invitations_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetLeaseSeconds() int32 {
	if x != nil {
		return x.LeaseSeconds
	}
	return 0
}

type ExpireSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpireSessionRequest) Reset() {
	*x = ExpireSessionRequest{}
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpireSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpireSessionRequest) ProtoMessage() {}

func (x *ExpireSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpireSessionRequest.ProtoReflect.Descriptor instead.
func (*ExpireSessionRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_sessions_invitations_proto_rawDescGZIP(), []int{4}
}

func (x *ExpireSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ExpireSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpireSessionResponse) Reset() {
	*x = ExpireSessionResponse{}
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpireSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpireSessionResponse) ProtoMessage() {}

func (x *ExpireSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpireSessionResponse.ProtoReflect.Descriptor instead.
func (*ExpireSessionResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_sessions_invitations_proto_rawDescGZIP(), []int{5}
}

type ResolveSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	TitleId       string                 `protobuf:"bytes,2,opt,name=title_id,json=titleId,proto3" json:"title_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveSessionRequest) Reset() {
	*x = ResolveSessionRequest{}
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveSessionRequest) ProtoMessage() {}

func (x *ResolveSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveSessionRequest.ProtoReflect.Descriptor instead.
func (*ResolveSessionRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_sessions_invitations_proto_rawDescGZIP(), []int{6}
}

func (x *ResolveSessionRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ResolveSessionRequest) GetTitleId() string {
	if x != nil {
		return x.TitleId
	}
	return ""
}

type ResolveSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	EndpointRef   string                 `protobuf:"bytes,3,opt,name=endpoint_ref,json=endpointRef,proto3" json:"endpoint_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveSessionResponse) Reset() {
	*x = ResolveSessionResponse{}
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveSessionResponse) ProtoMessage() {}

func (x *ResolveSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveSessionResponse.ProtoReflect.Descriptor instead.
func (*ResolveSessionResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_sessions_invitations_proto_rawDescGZIP(), []int{7}
}

func (x *ResolveSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ResolveSessionResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResolveSessionResponse) GetEndpointRef() string {
	if x != nil {
		return x.EndpointRef
	}
	return ""
}

type SendInvitationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAccountId string                 `protobuf:"bytes,1,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId   string                 `protobuf:"bytes,2,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	TitleId       string                 `protobuf:"bytes,3,opt,name=title_id,json=titleId,proto3" json:"title_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                          // opaque adapter content; server-capped at 4096 bytes
	TtlSeconds    int32                  `protobuf:"varint,5,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"` // required; cap 86400
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendInvitationRequest) Reset() {
	*x = SendInvitationRequest{}
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendInvitationRequest) ProtoMessage() {}

func (x *SendInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendInvitationRequest.ProtoReflect.Descriptor instead.
func (*SendInvitationRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_sessions_invitations_proto_rawDescGZIP(), []int{8}
}

func (x *SendInvitationRequest) GetFromAccountId() string {
	if x != nil {
		return x.FromAccountId
	}
	return ""
}

func (x *SendInvitationRequest) GetToAccountId() string {
	if x != nil {
		return x.ToAccountId
	}
	return ""
}

func (x *SendInvitationRequest) GetTitleId() string {
	if x != nil {
		return x.TitleId
	}
	return ""
}

func (x *SendInvitationRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SendInvitationRequest) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type SendInvitationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvitationId  string                 `protobuf:"bytes,1,opt,name=invitation_id,json=invitationId,proto3" json:"invitation_id,omitempty"`
	Nonce         string                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"` // caller echoes for replay rejection
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendInvitationResponse) Reset() {
	*x = SendInvitationResponse{}
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendInvitationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendInvitationResponse) ProtoMessage() {}

func (x *SendInvitationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendInvitationResponse.ProtoReflect.Descriptor instead.
func (*SendInvitationResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_sessions_invitations_proto_rawDescGZIP(), []int{9}
}

func (x *SendInvitationResponse) GetInvitationId() string {
	if x != nil {
		return x.InvitationId
	}
	return ""
}

func (x *SendInvitationResponse) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

type PollInvitationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"` // delivering adapter's own namespace
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollInvitationsRequest) Reset() {
	*x = PollInvitationsRequest{}
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollInvitationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollInvitationsRequest) ProtoMessage() {}

func (x *PollInvitationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollInvitationsRequest.ProtoReflect.Descriptor instead.
func (*PollInvitationsRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_sessions_invitations_proto_rawDescGZIP(), []int{10}
}

func (x *PollInvitationsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PollInvitationsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *PollInvitationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PollInvitationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invitations   []*Invitation          `protobuf:"bytes,1,rep,name=invitations,proto3" json:"invitations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollInvitationsResponse) Reset() {
	*x = PollInvitationsResponse{}
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollInvitationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollInvitationsResponse) ProtoMessage() {}

func (x *PollInvitationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollInvitationsResponse.ProtoReflect.Descriptor instead.
func (*PollInvitationsResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_sessions_invitations_proto_rawDescGZIP(), []int{11}
}

func (x *PollInvitationsResponse) GetInvitations() []*Invitation {
	if x != nil {
		return x.Invitations
	}
	return nil
}

type AckInvitationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	InvitationIds []string               `protobuf:"bytes,3,rep,name=invitation_ids,json=invitationIds,proto3" json:"invitation_ids,omitempty"`
	Nonces        []string               `protobuf:"bytes,4,rep,name=nonces,proto3" json:"nonces,omitempty"` // parallel to invitation_ids
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckInvitationsRequest) Reset() {
	*x = AckInvitationsRequest{}
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckInvitationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckInvitationsRequest) ProtoMessage() {}

func (x *AckInvitationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckInvitationsRequest.ProtoReflect.Descriptor instead.
func (*AckInvitationsRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_sessions_invitations_proto_rawDescGZIP(), []int{12}
}

func (x *AckInvitationsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AckInvitationsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AckInvitationsRequest) GetInvitationIds() []string {
	if x != nil {
		return x.InvitationIds
	}
	return nil
}

func (x *AckInvitationsRequest) GetNonces() []string {
	if x != nil {
		return x.Nonces
	}
	return nil
}

type AckInvitationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acked         int32                  `protobuf:"varint,1,opt,name=acked,proto3" json:"acked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckInvitationsResponse) Reset() {
	*x = AckInvitationsResponse{}
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckInvitationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckInvitationsResponse) ProtoMessage() {}

func (x *AckInvitationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckInvitationsResponse.ProtoReflect.Descriptor instead.
func (*AckInvitationsResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_sessions_invitations_proto_rawDescGZIP(), []int{13}
}

func (x *AckInvitationsResponse) GetAcked() int32 {
	if x != nil {
		return x.Acked
	}
	return 0
}

type Invitation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InvitationId    string                 `protobuf:"bytes,1,opt,name=invitation_id,json=invitationId,proto3" json:"invitation_id,omitempty"`
	FromAccountId   string                 `protobuf:"bytes,2,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	FromDisplayName string                 `protobuf:"bytes,3,opt,name=from_display_name,json=fromDisplayName,proto3" json:"from_display_name,omitempty"`
	TitleId         string                 `protobuf:"bytes,4,opt,name=title_id,json=titleId,proto3" json:"title_id,omitempty"`
	Payload         []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Nonce           string                 `protobuf:"bytes,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ExpiresAtUnix   int64                  `protobuf:"varint,7,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Invitation) Reset() {
	*x = Invitation{}
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invitation) ProtoMessage() {}

func (x *Invitation) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invitation.ProtoReflect.Descriptor instead.
func (*Invitation) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_sessions_invitations_proto_rawDescGZIP(), []int{14}
}

func (x *Invitation) GetInvitationId() string {
	if x != nil {
		return x.InvitationId
	}
	return ""
}

func (x *Invitation) GetFromAccountId() string {
	if x != nil {
		return x.FromAccountId
	}
	return ""
}

func (x *Invitation) GetFromDisplayName() string {
	if x != nil {
		return x.FromDisplayName
	}
	return ""
}

func (x *Invitation) GetTitleId() string {
	if x != nil {
		return x.TitleId
	}
	return ""
}

func (x *Invitation) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Invitation) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *Invitation) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

type GetPresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountIds    []string               `protobuf:"bytes,1,rep,name=account_ids,json=accountIds,proto3" json:"account_ids,omitempty"` // capped server-side at 200
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresenceRequest) Reset() {
	*x = GetPresenceRequest{}
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresenceRequest) ProtoMessage() {}

func (x *GetPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresenceRequest.ProtoReflect.Descriptor instead.
func (*GetPresenceRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_sessions_invitations_proto_rawDescGZIP(), []int{15}
}

func (x *GetPresenceRequest) GetAccountIds() []string {
	if x != nil {
		return x.AccountIds
	}
	return nil
}

type GetPresenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Presence      []*Presence            `protobuf:"bytes,1,rep,name=presence,proto3" json:"presence,omitempty"` // only accounts with a live session
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresenceResponse) Reset() {
	*x = GetPresenceResponse{}
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresenceResponse) ProtoMessage() {}

func (x *GetPresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresenceResponse.ProtoReflect.Descriptor instead.
func (*GetPresenceResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_sessions_invitations_proto_rawDescGZIP(), []int{16}
}

func (x *GetPresenceResponse) GetPresence() []*Presence {
	if x != nil {
		return x.Presence
	}
	return nil
}

type Presence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`                   // adapter the session belongs to
	TitleId       string                 `protobuf:"bytes,3,opt,name=title_id,json=titleId,proto3" json:"title_id,omitempty"`        // what they are playing; empty when the adapter sent none
	SinceUnix     int64                  `protobuf:"varint,4,opt,name=since_unix,json=sinceUnix,proto3" json:"since_unix,omitempty"` // when the session was registered
	NodeId        string                 `protobuf:"bytes,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`           // the federation node the session came through; "home" for the core's own adapters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Presence) Reset() {
	*x = Presence{}
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Presence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Presence) ProtoMessage() {}

func (x *Presence) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Presence.ProtoReflect.Descriptor instead.
func (*Presence) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_sessions_invitations_proto_rawDescGZIP(), []int{17}
}

func (x *Presence) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Presence) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Presence) GetTitleId() string {
	if x != nil {
		return x.TitleId
	}
	return ""
}

func (x *Presence) GetSinceUnix() int64 {
	if x != nil {
		return x.SinceUnix
	}
	return 0
}

func (x *Presence) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ListInvitationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // optional; server default and cap 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvitationsRequest) Reset() {
	*x = ListInvitationsRequest{}
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvitationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvitationsRequest) ProtoMessage() {}

func (x *ListInvitationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvitationsRequest.ProtoReflect.Descriptor instead.
func (*ListInvitationsRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_sessions_invitations_proto_rawDescGZIP(), []int{18}
}

func (x *ListInvitationsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListInvitationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListInvitationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invitations   []*InvitationSummary   `protobuf:"bytes,1,rep,name=invitations,proto3" json:"invitations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvitationsResponse) Reset() {
	*x = ListInvitationsResponse{}
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvitationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvitationsResponse) ProtoMessage() {}

func (x *ListInvitationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvitationsResponse.ProtoReflect.Descriptor instead.
func (*ListInvitationsResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_sessions_invitations_proto_rawDescGZIP(), []int{19}
}

func (x *ListInvitationsResponse) GetInvitations() []*InvitationSummary {
	if x != nil {
		return x.Invitations
	}
	return nil
}

// What a person may see about an invitation waiting for them. Deliberately not
// Invitation: payload and nonce are the delivering adapter's business.
type InvitationSummary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InvitationId    string                 `protobuf:"bytes,1,opt,name=invitation_id,json=invitationId,proto3" json:"invitation_id,omitempty"`
	FromAccountId   string                 `protobuf:"bytes,2,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	FromDisplayName string                 `protobuf:"bytes,3,opt,name=from_display_name,json=fromDisplayName,proto3" json:"from_display_name,omitempty"`
	TitleId         string                 `protobuf:"bytes,4,opt,name=title_id,json=titleId,proto3" json:"title_id,omitempty"`
	Namespace       string                 `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ExpiresAtUnix   int64                  `protobuf:"varint,6,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InvitationSummary) Reset() {
	*x = InvitationSummary{}
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvitationSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvitationSummary) ProtoMessage() {}

func (x *InvitationSummary) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvitationSummary.ProtoReflect.Descriptor instead.
func (*InvitationSummary) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_sessions_invitations_proto_rawDescGZIP(), []int{20}
}

func (x *InvitationSummary) GetInvitationId() string {
	if x != nil {
		return x.InvitationId
	}
	return ""
}

func (x *InvitationSummary) GetFromAccountId() string {
	if x != nil {
		return x.FromAccountId
	}
	return ""
}

func (x *InvitationSummary) GetFromDisplayName() string {
	if x != nil {
		return x.FromDisplayName
	}
	return ""
}

func (x *InvitationSummary) GetTitleId() string {
	if x != nil {
		return x.TitleId
	}
	return ""
}

func (x *InvitationSummary) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *InvitationSummary) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

type RejectInvitationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` // must be the recipient
	InvitationId  string                 `protobuf:"bytes,2,opt,name=invitation_id,json=invitationId,proto3" json:"invitation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectInvitationRequest) Reset() {
	*x = RejectInvitationRequest{}
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectInvitationRequest) ProtoMessage() {}

func (x *RejectInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectInvitationRequest.ProtoReflect.Descriptor instead.
func (*RejectInvitationRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_sessions_invitations_proto_rawDescGZIP(), []int{21}
}

func (x *RejectInvitationRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *RejectInvitationRequest) GetInvitationId() string {
	if x != nil {
		return x.InvitationId
	}
	return ""
}

type RejectInvitationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rejected      bool                   `protobuf:"varint,1,opt,name=rejected,proto3" json:"rejected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectInvitationResponse) Reset() {
	*x = RejectInvitationResponse{}
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectInvitationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectInvitationResponse) ProtoMessage() {}

func (x *RejectInvitationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectInvitationResponse.ProtoReflect.Descriptor instead.
func (*RejectInvitationResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_sessions_invitations_proto_rawDescGZIP(), []int{22}
}

func (x *RejectInvitationResponse) GetRejected() bool {
	if x != nil {
		return x.Rejected
	}
	return false
}

type GetPlayerCountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerCountsRequest) Reset() {
	*x = GetPlayerCountsRequest{}
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerCountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerCountsRequest) ProtoMessage() {}

func (x *GetPlayerCountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerCountsRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerCountsRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_sessions_invitations_proto_rawDescGZIP(), []int{23}
}

type GetPlayerCountsResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Titles       []*TitlePlayers        `protobuf:"bytes,1,rep,name=titles,proto3" json:"titles,omitempty"`
	TotalPlayers int32                  `protobuf:"varint,2,opt,name=total_players,json=totalPlayers,proto3" json:"total_players,omitempty"` // distinct accounts, not the sum of the rows
	// Per adapter namespace: one entry per console network with anybody on it.
	// Also distinct accounts, so someone playing two titles on the same network
	// is one player there.
	Networks []*NetworkPlayers `protobuf:"bytes,3,rep,name=networks,proto3" json:"networks,omitempty"`
	// Per federation node, distinct accounts. Where people are, for the status page.
	Nodes         []*NodePlayers `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerCountsResponse) Reset() {
	*x = GetPlayerCountsResponse{}
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerCountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerCountsResponse) ProtoMessage() {}

func (x *GetPlayerCountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerCountsResponse.ProtoReflect.Descriptor instead.
func (*GetPlayerCountsResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_sessions_invitations_proto_rawDescGZIP(), []int{24}
}

func (x *GetPlayerCountsResponse) GetTitles() []*TitlePlayers {
	if x != nil {
		return x.Titles
	}
	return nil
}

func (x *GetPlayerCountsResponse) GetTotalPlayers() int32 {
	if x != nil {
		return x.TotalPlayers
	}
	return 0
}

func (x *GetPlayerCountsResponse) GetNetworks() []*NetworkPlayers {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *GetPlayerCountsResponse) GetNodes() []*NodePlayers {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type NodePlayers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Players       int32                  `protobuf:"varint,2,opt,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodePlayers) Reset() {
	*x = NodePlayers{}
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodePlayers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodePlayers) ProtoMessage() {}

func (x *NodePlayers) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodePlayers.ProtoReflect.Descriptor instead.
func (*NodePlayers) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_sessions_invitations_proto_rawDescGZIP(), []int{25}
}

func (x *NodePlayers) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodePlayers) GetPlayers() int32 {
	if x != nil {
		return x.Players
	}
	return 0
}

type NetworkPlayers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Players       int32                  `protobuf:"varint,2,opt,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPlayers) Reset() {
	*x = NetworkPlayers{}
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPlayers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPlayers) ProtoMessage() {}

func (x *NetworkPlayers) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPlayers.ProtoReflect.Descriptor instead.
func (*NetworkPlayers) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_sessions_invitations_proto_rawDescGZIP(), []int{26}
}

func (x *NetworkPlayers) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *NetworkPlayers) GetPlayers() int32 {
	if x != nil {
		return x.Players
	}
	return 0
}

type TitlePlayers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TitleId       string                 `protobuf:"bytes,1,opt,name=title_id,json=titleId,proto3" json:"title_id,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Players       int32                  `protobuf:"varint,3,opt,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TitlePlayers) Reset() {
	*x = TitlePlayers{}
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TitlePlayers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitlePlayers) ProtoMessage() {}

func (x *TitlePlayers) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_sessions_invitations_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitlePlayers.ProtoReflect.Descriptor instead.
func (*TitlePlayers) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_sessions_invitations_proto_rawDescGZIP(), []int{27}
}

func (x *TitlePlayers) GetTitleId() string {
	if x != nil {
		return x.TitleId
	}
	return ""
}

func (x *TitlePlayers) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TitlePlayers) GetPlayers() int32 {
	if x != nil {
		return x.Players
	}
	return 0
}

var File_openpak_account_v1_sessions_invitations_proto protoreflect.FileDescriptor

const file_openpak_account_v1_sessions_invitations_proto_rawDesc = "" +
	"\n" +
	"-openpak/account/v1/sessions_invitations.proto\x12\x12openpak.account.v1\"\xb8\x01\n" +
	"\x16RegisterSessionRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x19\n" +
	"\btitle_id\x18\x03 \x01(\tR\atitleId\x12!\n" +
	"\fendpoint_ref\x18\x04 \x01(\tR\vendpointRef\x12#\n" +
	"\rlease_seconds\x18\x05 \x01(\x05R\fleaseSeconds\"]\n" +
	"\x17RegisterSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rlease_seconds\x18\x02 \x01(\x05R\fleaseSeconds\"1\n" +
	"\x10HeartbeatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"8\n" +
	"\x11HeartbeatResponse\x12#\n" +
	"\rlease_seconds\x18\x01 \x01(\x05R\fleaseSeconds\"5\n" +
	"\x14ExpireSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x17\n" +
	"\x15ExpireSessionResponse\"Q\n" +
	"\x15ResolveSessionRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x19\n" +
	"\btitle_id\x18\x02 \x01(\tR\atitleId\"x\n" +
	"\x16ResolveSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12!\n" +
	"\fendpoint_ref\x18\x03 \x01(\tR\vendpointRef\"\xb9\x01\n" +
	"\x15SendInvitationRequest\x12&\n" +
	"\x0ffrom_account_id\x18\x01 \x01(\tR\rfromAccountId\x12\"\n" +
	"\rto_account_id\x18\x02 \x01(\tR\vtoAccountId\x12\x19\n" +
	"\btitle_id\x18\x03 \x01(\tR\atitleId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1f\n" +
	"\vttl_seconds\x18\x05 \x01(\x05R\n" +
	"ttlSeconds\"S\n" +
	"\x16SendInvitationResponse\x12#\n" +
	"\rinvitation_id\x18\x01 \x01(\tR\finvitationId\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\tR\x05nonce\"k\n" +
	"\x16PollInvitationsRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"[\n" +
	"\x17PollInvitationsResponse\x12@\n" +
	"\vinvitations\x18\x01 \x03(\v2\x1e.openpak.account.v1.InvitationR\vinvitations\"\x93\x01\n" +
	"\x15AckInvitationsRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12%\n" +
	"\x0einvitation_ids\x18\x03 \x03(\tR\rinvitationIds\x12\x16\n" +
	"\x06nonces\x18\x04 \x03(\tR\x06nonces\".\n" +
	"\x16AckInvitationsResponse\x12\x14\n" +
	"\x05acked\x18\x01 \x01(\x05R\x05acked\"\xf8\x01\n" +
	"\n" +
	"Invitation\x12#\n" +
	"\rinvitation_id\x18\x01 \x01(\tR\finvitationId\x12&\n" +
	"\x0ffrom_account_id\x18\x02 \x01(\tR\rfromAccountId\x12*\n" +
	"\x11from_display_name\x18\x03 \x01(\tR\x0ffromDisplayName\x12\x19\n" +
	"\btitle_id\x18\x04 \x01(\tR\atitleId\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\tR\x05nonce\x12&\n" +
	"\x0fexpires_at_unix\x18\a \x01(\x03R\rexpiresAtUnix\"5\n" +
	"\x12GetPresenceRequest\x12\x1f\n" +
	"\vaccount_ids\x18\x01 \x03(\tR\n" +
	"accountIds\"O\n" +
	"\x13GetPresenceResponse\x128\n" +
	"\bpresence\x18\x01 \x03(\v2\x1c.openpak.account.v1.PresenceR\bpresence\"\x9a\x01\n" +
	"\bPresence\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x19\n" +
	"\btitle_id\x18\x03 \x01(\tR\atitleId\x12\x1d\n" +
	"\n" +
	"since_unix\x18\x04 \x01(\x03R\tsinceUnix\x12\x17\n" +
	"\anode_id\x18\x05 \x01(\tR\x06nodeId\"M\n" +
	"\x16ListInvitationsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"b\n" +
	"\x17ListInvitationsResponse\x12G\n" +
	"\vinvitations\x18\x01 \x03(\v2%.openpak.account.v1.InvitationSummaryR\vinvitations\"\xed\x01\n" +
	"\x11InvitationSummary\x12#\n" +
	"\rinvitation_id\x18\x01 \x01(\tR\finvitationId\x12&\n" +
	"\x0ffrom_account_id\x18\x02 \x01(\tR\rfromAccountId\x12*\n" +
	"\x11from_display_name\x18\x03 \x01(\tR\x0ffromDisplayName\x12\x19\n" +
	"\btitle_id\x18\x04 \x01(\tR\atitleId\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12&\n" +
	"\x0fexpires_at_unix\x18\x06 \x01(\x03R\rexpiresAtUnix\"]\n" +
	"\x17RejectInvitationRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12#\n" +
	"\rinvitation_id\x18\x02 \x01(\tR\finvitationId\"6\n" +
	"\x18RejectInvitationResponse\x12\x1a\n" +
	"\brejected\x18\x01 \x01(\bR\brejected\"\x18\n" +
	"\x16GetPlayerCountsRequest\"\xef\x01\n" +
	"\x17GetPlayerCountsResponse\x128\n" +
	"\x06titles\x18\x01 \x03(\v2 .openpak.account.v1.TitlePlayersR\x06titles\x12#\n" +
	"\rtotal_players\x18\x02 \x01(\x05R\ftotalPlayers\x12>\n" +
	"\bnetworks\x18\x03 \x03(\v2\".openpak.account.v1.NetworkPlayersR\bnetworks\x125\n" +
	"\x05nodes\x18\x04 \x03(\v2\x1f.openpak.account.v1.NodePlayersR\x05nodes\"@\n" +
	"\vNodePlayers\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aplayers\x18\x02 \x01(\x05R\aplayers\"H\n" +
	"\x0eNetworkPlayers\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x18\n" +
	"\aplayers\x18\x02 \x01(\x05R\aplayers\"a\n" +
	"\fTitlePlayers\x12\x19\n" +
	"\btitle_id\x18\x01 \x01(\tR\atitleId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x18\n" +
	"\aplayers\x18\x03 \x01(\x05R\aplayers2\xeb\x04\n" +
	"\bSessions\x12j\n" +
	"\x0fRegisterSession\x12*.openpak.account.v1.RegisterSessionRequest\x1a+.openpak.account.v1.RegisterSessionResponse\x12X\n" +
	"\tHeartbeat\x12$.openpak.account.v1.HeartbeatRequest\x1a%.openpak.account.v1.HeartbeatResponse\x12d\n" +
	"\rExpireSession\x12(.openpak.account.v1.ExpireSessionRequest\x1a).openpak.account.v1.ExpireSessionResponse\x12g\n" +
	"\x0eResolveSession\x12).openpak.account.v1.ResolveSessionRequest\x1a*.openpak.account.v1.ResolveSessionResponse\x12^\n" +
	"\vGetPresence\x12&.openpak.account.v1.GetPresenceRequest\x1a'.openpak.account.v1.GetPresenceResponse\x12j\n" +
	"\x0fGetPlayerCounts\x12*.openpak.account.v1.GetPlayerCountsRequest\x1a+.openpak.account.v1.GetPlayerCountsResponse2\xa6\x04\n" +
	"\vInvitations\x12g\n" +
	"\x0eSendInvitation\x12).openpak.account.v1.SendInvitationRequest\x1a*.openpak.account.v1.SendInvitationResponse\x12j\n" +
	"\x0fPollInvitations\x12*.openpak.account.v1.PollInvitationsRequest\x1a+.openpak.account.v1.PollInvitationsResponse\x12g\n" +
	"\x0eAckInvitations\x12).openpak.account.v1.AckInvitationsRequest\x1a*.openpak.account.v1.AckInvitationsResponse\x12j\n" +
	"\x0fListInvitations\x12*.openpak.account.v1.ListInvitationsRequest\x1a+.openpak.account.v1.ListInvitationsResponse\x12m\n" +
	"\x10RejectInvitation\x12+.openpak.account.v1.RejectInvitationRequest\x1a,.openpak.account.v1.RejectInvitationResponseB4Z2openpak/account/proto/openpak/account/v1;accountv1b\x06proto3"

var (
	file_openpak_account_v1_sessions_invitations_proto_rawDescOnce sync.Once
	file_openpak_account_v1_sessions_invitations_proto_rawDescData []byte
)

func file_openpak_account_v1_sessions_invitations_proto_rawDescGZIP() []byte {
	file_openpak_account_v1_sessions_invitations_proto_rawDescOnce.Do(func() {
		file_openpak_account_v1_sessions_invitations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openpak_account_v1_sessions_invitations_proto_rawDesc), len(file_openpak_account_v1_sessions_invitations_proto_rawDesc)))
	})
	return file_openpak_account_v1_sessions_invitations_proto_rawDescData
}

var file_openpak_account_v1_sessions_invitations_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_openpak_account_v1_sessions_invitations_proto_goTypes = []any{
	(*RegisterSessionRequest)(nil),   // 0: openpak.account.v1.RegisterSessionRequest
	(*RegisterSessionResponse)(nil),  // 1: openpak.account.v1.RegisterSessionResponse
	(*HeartbeatRequest)(nil),         // 2: openpak.account.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),        // 3: openpak.account.v1.HeartbeatResponse
	(*ExpireSessionRequest)(nil),     // 4: openpak.account.v1.ExpireSessionRequest
	(*ExpireSessionResponse)(nil),    // 5: openpak.account.v1.ExpireSessionResponse
	(*ResolveSessionRequest)(nil),    // 6: openpak.account.v1.ResolveSessionRequest
	(*ResolveSessionResponse)(nil),   // 7: openpak.account.v1.ResolveSessionResponse
	(*SendInvitationRequest)(nil),    // 8: openpak.account.v1.SendInvitationRequest
	(*SendInvitationResponse)(nil),   // 9: openpak.account.v1.SendInvitationResponse
	(*PollInvitationsRequest)(nil),   // 10: openpak.account.v1.PollInvitationsRequest
	(*PollInvitationsResponse)(nil),  // 11: openpak.account.v1.PollInvitationsResponse
	(*AckInvitationsRequest)(nil),    // 12: openpak.account.v1.AckInvitationsRequest
	(*AckInvitationsResponse)(nil),   // 13: openpak.account.v1.AckInvitationsResponse
	(*Invitation)(nil),               // 14: openpak.account.v1.Invitation
	(*GetPresenceRequest)(nil),       // 15: openpak.account.v1.GetPresenceRequest
	(*GetPresenceResponse)(nil),      // 16: openpak.account.v1.GetPresenceResponse
	(*Presence)(nil),                 // 17: openpak.account.v1.Presence
	(*ListInvitationsRequest)(nil),   // 18: openpak.account.v1.ListInvitationsRequest
	(*ListInvitationsResponse)(nil),  // 19: openpak.account.v1.ListInvitationsResponse
	(*InvitationSummary)(nil),        // 20: openpak.account.v1.InvitationSummary
	(*RejectInvitationRequest)(nil),  // 21: openpak.account.v1.RejectInvitationRequest
	(*RejectInvitationResponse)(nil), // 22: openpak.account.v1.RejectInvitationResponse
	(*GetPlayerCountsRequest)(nil),   // 23: openpak.account.v1.GetPlayerCountsRequest
	(*GetPlayerCountsResponse)(nil),  // 24: openpak.account.v1.GetPlayerCountsResponse
	(*NodePlayers)(nil),              // 25: openpak.account.v1.NodePlayers
	(*NetworkPlayers)(nil),           // 26: openpak.account.v1.NetworkPlayers
	(*TitlePlayers)(nil),             // 27: openpak.account.v1.TitlePlayers
}
var file_openpak_account_v1_sessions_invitations_proto_depIdxs = []int32{
	14, // 0: openpak.account.v1.PollInvitationsResponse.invitations:type_name -> openpak.account.v1.Invitation
	17, // 1: openpak.account.v1.GetPresenceResponse.presence:type_name -> openpak.account.v1.Presence
	20, // 2: openpak.account.v1.ListInvitationsResponse.invitations:type_name -> openpak.account.v1.InvitationSummary
	27, // 3: openpak.account.v1.GetPlayerCountsResponse.titles:type_name -> openpak.account.v1.TitlePlayers
	26, // 4: openpak.account.v1.GetPlayerCountsResponse.networks:type_name -> openpak.account.v1.NetworkPlayers
	25, // 5: openpak.account.v1.GetPlayerCountsResponse.nodes:type_name -> openpak.account.v1.NodePlayers
	0,  // 6: openpak.account.v1.Sessions.RegisterSession:input_type -> openpak.account.v1.RegisterSessionRequest
	2,  // 7: openpak.account.v1.Sessions.Heartbeat:input_type -> openpak.account.v1.HeartbeatRequest
	4,  // 8: openpak.account.v1.Sessions.ExpireSession:input_type -> openpak.account.v1.ExpireSessionRequest
	6,  // 9: openpak.account.v1.Sessions.ResolveSession:input_type -> openpak.account.v1.ResolveSessionRequest
	15, // 10: openpak.account.v1.Sessions.GetPresence:input_type -> openpak.account.v1.GetPresenceRequest
	23, // 11: openpak.account.v1.Sessions.GetPlayerCounts:input_type -> openpak.account.v1.GetPlayerCountsRequest
	8,  // 12: openpak.account.v1.Invitations.SendInvitation:input_type -> openpak.account.v1.SendInvitationRequest
	10, // 13: openpak.account.v1.Invitations.PollInvitations:input_type -> openpak.account.v1.PollInvitationsRequest
	12, // 14: openpak.account.v1.Invitations.AckInvitations:input_type -> openpak.account.v1.AckInvitationsRequest
	18, // 15: openpak.account.v1.Invitations.ListInvitations:input_type -> openpak.account.v1.ListInvitationsRequest
	21, // 16: openpak.account.v1.Invitations.RejectInvitation:input_type -> openpak.account.v1.RejectInvitationRequest
	1,  // 17: openpak.account.v1.Sessions.RegisterSession:output_type -> openpak.account.v1.RegisterSessionResponse
	3,  // 18: openpak.account.v1.Sessions.Heartbeat:output_type -> openpak.account.v1.HeartbeatResponse
	5,  // 19: openpak.account.v1.Sessions.ExpireSession:output_type -> openpak.account.v1.ExpireSessionResponse
	7,  // 20: openpak.account.v1.Sessions.ResolveSession:output_type -> openpak.account.v1.ResolveSessionResponse
	16, // 21: openpak.account.v1.Sessions.GetPresence:output_type -> openpak.account.v1.GetPresenceResponse
	24, // 22: openpak.account.v1.Sessions.GetPlayerCounts:output_type -> openpak.account.v1.GetPlayerCountsResponse
	9,  // 23: openpak.account.v1.Invitations.SendInvitation:output_type -> openpak.account.v1.SendInvitationResponse
	11, // 24: openpak.account.v1.Invitations.PollInvitations:output_type -> openpak.account.v1.PollInvitationsResponse
	13, // 25: openpak.account.v1.Invitations.AckInvitations:output_type -> openpak.account.v1.AckInvitationsResponse
	19, // 26: openpak.account.v1.Invitations.ListInvitations:output_type -> openpak.account.v1.ListInvitationsResponse
	22, // 27: openpak.account.v1.Invitations.RejectInvitation:output_type -> openpak.account.v1.RejectInvitationResponse
	17, // [17:28] is the sub-list for method output_type
	6,  // [6:17] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_openpak_account_v1_sessions_invitations_proto_init() }
func file_openpak_account_v1_sessions_invitations_proto_init() {
	if File_openpak_account_v1_sessions_invitations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openpak_account_v1_sessions_invitations_proto_rawDesc), len(file_openpak_account_v1_sessions_invitations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_openpak_account_v1_sessions_invitations_proto_goTypes,
		DependencyIndexes: file_openpak_account_v1_sessions_invitations_proto_depIdxs,
		MessageInfos:      file_openpak_account_v1_sessions_invitations_proto_msgTypes,
	}.Build()
	File_openpak_account_v1_sessions_invitations_proto = out.File
	file_openpak_account_v1_sessions_invitations_proto_goTypes = nil
	file_openpak_account_v1_sessions_invitations_proto_depIdxs = nil
}
