// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: openpak/account/v1/social.proto

package accountv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Social_RequestFriend_FullMethodName        = "/openpak.account.v1.Social/RequestFriend"
	Social_AcceptFriend_FullMethodName         = "/openpak.account.v1.Social/AcceptFriend"
	Social_RemoveFriend_FullMethodName         = "/openpak.account.v1.Social/RemoveFriend"
	Social_ListFriends_FullMethodName          = "/openpak.account.v1.Social/ListFriends"
	Social_ListIncomingRequests_FullMethodName = "/openpak.account.v1.Social/ListIncomingRequests"
	Social_ListOutgoingRequests_FullMethodName = "/openpak.account.v1.Social/ListOutgoingRequests"
	Social_GetRelationship_FullMethodName      = "/openpak.account.v1.Social/GetRelationship"
	Social_CheckInteraction_FullMethodName     = "/openpak.account.v1.Social/CheckInteraction"
	Social_Block_FullMethodName                = "/openpak.account.v1.Social/Block"
	Social_Unblock_FullMethodName              = "/openpak.account.v1.Social/Unblock"
)

// SocialClient is the client API for Social service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Canonical friend graph and interaction enforcement (PRD SW-05). The core
// owns relationships and blocks; adapters receive projections and answers,
// never another authoritative store. Friend-request lifecycle is core-side.
type SocialClient interface {
	// Request friendship (state: pending until the addressee accepts).
	// Idempotent while pending; self-requests are rejected.
	RequestFriend(ctx context.Context, in *RequestFriendRequest, opts ...grpc.CallOption) (*RequestFriendResponse, error)
	// Accept a pending incoming request. Fails unless pending.
	AcceptFriend(ctx context.Context, in *AcceptFriendRequest, opts ...grpc.CallOption) (*AcceptFriendResponse, error)
	// Remove an accepted friendship (either side). Idempotent when absent.
	RemoveFriend(ctx context.Context, in *RemoveFriendRequest, opts ...grpc.CallOption) (*RemoveFriendResponse, error)
	// Accepted friends with minimal profile projection.
	ListFriends(ctx context.Context, in *ListFriendsRequest, opts ...grpc.CallOption) (*ListFriendsResponse, error)
	// Pending incoming requests for an account.
	ListIncomingRequests(ctx context.Context, in *ListIncomingRequestsRequest, opts ...grpc.CallOption) (*ListIncomingRequestsResponse, error)
	// Pending requests the account SENT (Wii U protocol needs both sides).
	ListOutgoingRequests(ctx context.Context, in *ListOutgoingRequestsRequest, opts ...grpc.CallOption) (*ListOutgoingRequestsResponse, error)
	// Relationship between two accounts from the first account's viewpoint.
	GetRelationship(ctx context.Context, in *GetRelationshipRequest, opts ...grpc.CallOption) (*GetRelationshipResponse, error)
	// Enforcement answer for a directed interaction (discovery, invitation,
	// message). Consults friendship, blocks, and account status; privacy
	// broadening beyond friendship is future work (see SP-5 draft).
	CheckInteraction(ctx context.Context, in *CheckInteractionRequest, opts ...grpc.CallOption) (*CheckInteractionResponse, error)
	// Block an account (durable, directional). Unfriend effect is explicit:
	// blocking does not remove an existing friendship row; enforcement still
	// denies interactions while a block exists.
	Block(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (*BlockResponse, error)
	Unblock(ctx context.Context, in *UnblockRequest, opts ...grpc.CallOption) (*UnblockResponse, error)
}

type socialClient struct {
	cc grpc.ClientConnInterface
}

func NewSocialClient(cc grpc.ClientConnInterface) SocialClient {
	return &socialClient{cc}
}

func (c *socialClient) RequestFriend(ctx context.Context, in *RequestFriendRequest, opts ...grpc.CallOption) (*RequestFriendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestFriendResponse)
	err := c.cc.Invoke(ctx, Social_RequestFriend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) AcceptFriend(ctx context.Context, in *AcceptFriendRequest, opts ...grpc.CallOption) (*AcceptFriendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptFriendResponse)
	err := c.cc.Invoke(ctx, Social_AcceptFriend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) RemoveFriend(ctx context.Context, in *RemoveFriendRequest, opts ...grpc.CallOption) (*RemoveFriendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveFriendResponse)
	err := c.cc.Invoke(ctx, Social_RemoveFriend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) ListFriends(ctx context.Context, in *ListFriendsRequest, opts ...grpc.CallOption) (*ListFriendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFriendsResponse)
	err := c.cc.Invoke(ctx, Social_ListFriends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) ListIncomingRequests(ctx context.Context, in *ListIncomingRequestsRequest, opts ...grpc.CallOption) (*ListIncomingRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIncomingRequestsResponse)
	err := c.cc.Invoke(ctx, Social_ListIncomingRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) ListOutgoingRequests(ctx context.Context, in *ListOutgoingRequestsRequest, opts ...grpc.CallOption) (*ListOutgoingRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOutgoingRequestsResponse)
	err := c.cc.Invoke(ctx, Social_ListOutgoingRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GetRelationship(ctx context.Context, in *GetRelationshipRequest, opts ...grpc.CallOption) (*GetRelationshipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRelationshipResponse)
	err := c.cc.Invoke(ctx, Social_GetRelationship_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) CheckInteraction(ctx context.Context, in *CheckInteractionRequest, opts ...grpc.CallOption) (*CheckInteractionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckInteractionResponse)
	err := c.cc.Invoke(ctx, Social_CheckInteraction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) Block(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (*BlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlockResponse)
	err := c.cc.Invoke(ctx, Social_Block_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) Unblock(ctx context.Context, in *UnblockRequest, opts ...grpc.CallOption) (*UnblockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnblockResponse)
	err := c.cc.Invoke(ctx, Social_Unblock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SocialServer is the server API for Social service.
// All implementations must embed UnimplementedSocialServer
// for forward compatibility.
//
// Canonical friend graph and interaction enforcement (PRD SW-05). The core
// owns relationships and blocks; adapters receive projections and answers,
// never another authoritative store. Friend-request lifecycle is core-side.
type SocialServer interface {
	// Request friendship (state: pending until the addressee accepts).
	// Idempotent while pending; self-requests are rejected.
	RequestFriend(context.Context, *RequestFriendRequest) (*RequestFriendResponse, error)
	// Accept a pending incoming request. Fails unless pending.
	AcceptFriend(context.Context, *AcceptFriendRequest) (*AcceptFriendResponse, error)
	// Remove an accepted friendship (either side). Idempotent when absent.
	RemoveFriend(context.Context, *RemoveFriendRequest) (*RemoveFriendResponse, error)
	// Accepted friends with minimal profile projection.
	ListFriends(context.Context, *ListFriendsRequest) (*ListFriendsResponse, error)
	// Pending incoming requests for an account.
	ListIncomingRequests(context.Context, *ListIncomingRequestsRequest) (*ListIncomingRequestsResponse, error)
	// Pending requests the account SENT (Wii U protocol needs both sides).
	ListOutgoingRequests(context.Context, *ListOutgoingRequestsRequest) (*ListOutgoingRequestsResponse, error)
	// Relationship between two accounts from the first account's viewpoint.
	GetRelationship(context.Context, *GetRelationshipRequest) (*GetRelationshipResponse, error)
	// Enforcement answer for a directed interaction (discovery, invitation,
	// message). Consults friendship, blocks, and account status; privacy
	// broadening beyond friendship is future work (see SP-5 draft).
	CheckInteraction(context.Context, *CheckInteractionRequest) (*CheckInteractionResponse, error)
	// Block an account (durable, directional). Unfriend effect is explicit:
	// blocking does not remove an existing friendship row; enforcement still
	// denies interactions while a block exists.
	Block(context.Context, *BlockRequest) (*BlockResponse, error)
	Unblock(context.Context, *UnblockRequest) (*UnblockResponse, error)
	mustEmbedUnimplementedSocialServer()
}

// UnimplementedSocialServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSocialServer struct{}

func (UnimplementedSocialServer) RequestFriend(context.Context, *RequestFriendRequest) (*RequestFriendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestFriend not implemented")
}
func (UnimplementedSocialServer) AcceptFriend(context.Context, *AcceptFriendRequest) (*AcceptFriendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptFriend not implemented")
}
func (UnimplementedSocialServer) RemoveFriend(context.Context, *RemoveFriendRequest) (*RemoveFriendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveFriend not implemented")
}
func (UnimplementedSocialServer) ListFriends(context.Context, *ListFriendsRequest) (*ListFriendsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFriends not implemented")
}
func (UnimplementedSocialServer) ListIncomingRequests(context.Context, *ListIncomingRequestsRequest) (*ListIncomingRequestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIncomingRequests not implemented")
}
func (UnimplementedSocialServer) ListOutgoingRequests(context.Context, *ListOutgoingRequestsRequest) (*ListOutgoingRequestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOutgoingRequests not implemented")
}
func (UnimplementedSocialServer) GetRelationship(context.Context, *GetRelationshipRequest) (*GetRelationshipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRelationship not implemented")
}
func (UnimplementedSocialServer) CheckInteraction(context.Context, *CheckInteractionRequest) (*CheckInteractionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckInteraction not implemented")
}
func (UnimplementedSocialServer) Block(context.Context, *BlockRequest) (*BlockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Block not implemented")
}
func (UnimplementedSocialServer) Unblock(context.Context, *UnblockRequest) (*UnblockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Unblock not implemented")
}
func (UnimplementedSocialServer) mustEmbedUnimplementedSocialServer() {}
func (UnimplementedSocialServer) testEmbeddedByValue()                {}

// UnsafeSocialServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SocialServer will
// result in compilation errors.
type UnsafeSocialServer interface {
	mustEmbedUnimplementedSocialServer()
}

func RegisterSocialServer(s grpc.ServiceRegistrar, srv SocialServer) {
	// If the following call panics, it indicates UnimplementedSocialServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Social_ServiceDesc, srv)
}

func _Social_RequestFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).RequestFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_RequestFriend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).RequestFriend(ctx, req.(*RequestFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_AcceptFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).AcceptFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_AcceptFriend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).AcceptFriend(ctx, req.(*AcceptFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_RemoveFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).RemoveFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_RemoveFriend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).RemoveFriend(ctx, req.(*RemoveFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_ListFriends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFriendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).ListFriends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_ListFriends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).ListFriends(ctx, req.(*ListFriendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_ListIncomingRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIncomingRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).ListIncomingRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_ListIncomingRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).ListIncomingRequests(ctx, req.(*ListIncomingRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_ListOutgoingRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOutgoingRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).ListOutgoingRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_ListOutgoingRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).ListOutgoingRequests(ctx, req.(*ListOutgoingRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GetRelationship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRelationshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GetRelationship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GetRelationship_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GetRelationship(ctx, req.(*GetRelationshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_CheckInteraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckInteractionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).CheckInteraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_CheckInteraction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).CheckInteraction(ctx, req.(*CheckInteractionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_Block_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).Block(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_Block_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).Block(ctx, req.(*BlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_Unblock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnblockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).Unblock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_Unblock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).Unblock(ctx, req.(*UnblockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Social_ServiceDesc is the grpc.ServiceDesc for Social service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Social_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openpak.account.v1.Social",
	HandlerType: (*SocialServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestFriend",
			Handler:    _Social_RequestFriend_Handler,
		},
		{
			MethodName: "AcceptFriend",
			Handler:    _Social_AcceptFriend_Handler,
		},
		{
			MethodName: "RemoveFriend",
			Handler:    _Social_RemoveFriend_Handler,
		},
		{
			MethodName: "ListFriends",
			Handler:    _Social_ListFriends_Handler,
		},
		{
			MethodName: "ListIncomingRequests",
			Handler:    _Social_ListIncomingRequests_Handler,
		},
		{
			MethodName: "ListOutgoingRequests",
			Handler:    _Social_ListOutgoingRequests_Handler,
		},
		{
			MethodName: "GetRelationship",
			Handler:    _Social_GetRelationship_Handler,
		},
		{
			MethodName: "CheckInteraction",
			Handler:    _Social_CheckInteraction_Handler,
		},
		{
			MethodName: "Block",
			Handler:    _Social_Block_Handler,
		},
		{
			MethodName: "Unblock",
			Handler:    _Social_Unblock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "openpak/account/v1/social.proto",
}
