// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: openpak/account/v1/social.proto

package accountv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Relationship int32

const (
	Relationship_RELATIONSHIP_UNSPECIFIED      Relationship = 0
	Relationship_RELATIONSHIP_NONE             Relationship = 1
	Relationship_RELATIONSHIP_PENDING_INCOMING Relationship = 2 // other requested account_id
	Relationship_RELATIONSHIP_PENDING_OUTGOING Relationship = 3 // account_id requested other
	Relationship_RELATIONSHIP_FRIENDS          Relationship = 4
	Relationship_RELATIONSHIP_BLOCKED_BY_SELF  Relationship = 5
	Relationship_RELATIONSHIP_BLOCKED_BY_OTHER Relationship = 6
)

// Enum value maps for Relationship.
var (
	Relationship_name = map[int32]string{
		0: "RELATIONSHIP_UNSPECIFIED",
		1: "RELATIONSHIP_NONE",
		2: "RELATIONSHIP_PENDING_INCOMING",
		3: "RELATIONSHIP_PENDING_OUTGOING",
		4: "RELATIONSHIP_FRIENDS",
		5: "RELATIONSHIP_BLOCKED_BY_SELF",
		6: "RELATIONSHIP_BLOCKED_BY_OTHER",
	}
	Relationship_value = map[string]int32{
		"RELATIONSHIP_UNSPECIFIED":      0,
		"RELATIONSHIP_NONE":             1,
		"RELATIONSHIP_PENDING_INCOMING": 2,
		"RELATIONSHIP_PENDING_OUTGOING": 3,
		"RELATIONSHIP_FRIENDS":          4,
		"RELATIONSHIP_BLOCKED_BY_SELF":  5,
		"RELATIONSHIP_BLOCKED_BY_OTHER": 6,
	}
)

func (x Relationship) Enum() *Relationship {
	p := new(Relationship)
	*p = x
	return p
}

func (x Relationship) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Relationship) Descriptor() protoreflect.EnumDescriptor {
	return file_openpak_account_v1_social_proto_enumTypes[0].Descriptor()
}

func (Relationship) Type() protoreflect.EnumType {
	return &file_openpak_account_v1_social_proto_enumTypes[0]
}

func (x Relationship) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Relationship.Descriptor instead.
func (Relationship) EnumDescriptor() ([]byte, []int) {
	return file_openpak_account_v1_social_proto_rawDescGZIP(), []int{0}
}

type InteractionKind int32

const (
	InteractionKind_INTERACTION_KIND_UNSPECIFIED InteractionKind = 0
	InteractionKind_INTERACTION_KIND_DISCOVER    InteractionKind = 1 // e.g. listing the target's session/farm
	InteractionKind_INTERACTION_KIND_INVITE      InteractionKind = 2
	InteractionKind_INTERACTION_KIND_MESSAGE     InteractionKind = 3
)

// Enum value maps for InteractionKind.
var (
	InteractionKind_name = map[int32]string{
		0: "INTERACTION_KIND_UNSPECIFIED",
		1: "INTERACTION_KIND_DISCOVER",
		2: "INTERACTION_KIND_INVITE",
		3: "INTERACTION_KIND_MESSAGE",
	}
	InteractionKind_value = map[string]int32{
		"INTERACTION_KIND_UNSPECIFIED": 0,
		"INTERACTION_KIND_DISCOVER":    1,
		"INTERACTION_KIND_INVITE":      2,
		"INTERACTION_KIND_MESSAGE":     3,
	}
)

func (x InteractionKind) Enum() *InteractionKind {
	p := new(InteractionKind)
	*p = x
	return p
}

func (x InteractionKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InteractionKind) Descriptor() protoreflect.EnumDescriptor {
	return file_openpak_account_v1_social_proto_enumTypes[1].Descriptor()
}

func (InteractionKind) Type() protoreflect.EnumType {
	return &file_openpak_account_v1_social_proto_enumTypes[1]
}

func (x InteractionKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InteractionKind.Descriptor instead.
func (InteractionKind) EnumDescriptor() ([]byte, []int) {
	return file_openpak_account_v1_social_proto_rawDescGZIP(), []int{1}
}

type DenialReason int32

const (
	DenialReason_DENIAL_REASON_UNSPECIFIED      DenialReason = 0
	DenialReason_DENIAL_REASON_ALLOWED          DenialReason = 1
	DenialReason_DENIAL_REASON_BLOCKED          DenialReason = 2
	DenialReason_DENIAL_REASON_NOT_FRIENDS      DenialReason = 3
	DenialReason_DENIAL_REASON_ACCOUNT_INACTIVE DenialReason = 4
	DenialReason_DENIAL_REASON_SELF             DenialReason = 5
)

// Enum value maps for DenialReason.
var (
	DenialReason_name = map[int32]string{
		0: "DENIAL_REASON_UNSPECIFIED",
		1: "DENIAL_REASON_ALLOWED",
		2: "DENIAL_REASON_BLOCKED",
		3: "DENIAL_REASON_NOT_FRIENDS",
		4: "DENIAL_REASON_ACCOUNT_INACTIVE",
		5: "DENIAL_REASON_SELF",
	}
	DenialReason_value = map[string]int32{
		"DENIAL_REASON_UNSPECIFIED":      0,
		"DENIAL_REASON_ALLOWED":          1,
		"DENIAL_REASON_BLOCKED":          2,
		"DENIAL_REASON_NOT_FRIENDS":      3,
		"DENIAL_REASON_ACCOUNT_INACTIVE": 4,
		"DENIAL_REASON_SELF":             5,
	}
)

func (x DenialReason) Enum() *DenialReason {
	p := new(DenialReason)
	*p = x
	return p
}

func (x DenialReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DenialReason) Descriptor() protoreflect.EnumDescriptor {
	return file_openpak_account_v1_social_proto_enumTypes[2].Descriptor()
}

func (DenialReason) Type() protoreflect.EnumType {
	return &file_openpak_account_v1_social_proto_enumTypes[2]
}

func (x DenialReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DenialReason.Descriptor instead.
func (DenialReason) EnumDescriptor() ([]byte, []int) {
	return file_openpak_account_v1_social_proto_rawDescGZIP(), []int{2}
}

type FriendState int32

const (
	FriendState_FRIEND_STATE_UNSPECIFIED FriendState = 0
	FriendState_FRIEND_STATE_PENDING     FriendState = 1
	FriendState_FRIEND_STATE_ACCEPTED    FriendState = 2
)

// Enum value maps for FriendState.
var (
	FriendState_name = map[int32]string{
		0: "FRIEND_STATE_UNSPECIFIED",
		1: "FRIEND_STATE_PENDING",
		2: "FRIEND_STATE_ACCEPTED",
	}
	FriendState_value = map[string]int32{
		"FRIEND_STATE_UNSPECIFIED": 0,
		"FRIEND_STATE_PENDING":     1,
		"FRIEND_STATE_ACCEPTED":    2,
	}
)

func (x FriendState) Enum() *FriendState {
	p := new(FriendState)
	*p = x
	return p
}

func (x FriendState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FriendState) Descriptor() protoreflect.EnumDescriptor {
	return file_openpak_account_v1_social_proto_enumTypes[3].Descriptor()
}

func (FriendState) Type() protoreflect.EnumType {
	return &file_openpak_account_v1_social_proto_enumTypes[3]
}

func (x FriendState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FriendState.Descriptor instead.
func (FriendState) EnumDescriptor() ([]byte, []int) {
	return file_openpak_account_v1_social_proto_rawDescGZIP(), []int{3}
}

type RequestFriendRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequesterId    string                 `protobuf:"bytes,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	AddresseeId    string                 `protobuf:"bytes,2,opt,name=addressee_id,json=addresseeId,proto3" json:"addressee_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestFriendRequest) Reset() {
	*x = RequestFriendRequest{}
	mi := &file_openpak_account_v1_social_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestFriendRequest) ProtoMessage() {}

func (x *RequestFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_social_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestFriendRequest.ProtoReflect.Descriptor instead.
func (*RequestFriendRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_social_proto_rawDescGZIP(), []int{0}
}

func (x *RequestFriendRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *RequestFriendRequest) GetAddresseeId() string {
	if x != nil {
		return x.AddresseeId
	}
	return ""
}

func (x *RequestFriendRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type RequestFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendshipId  string                 `protobuf:"bytes,1,opt,name=friendship_id,json=friendshipId,proto3" json:"friendship_id,omitempty"`
	State         FriendState            `protobuf:"varint,2,opt,name=state,proto3,enum=openpak.account.v1.FriendState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestFriendResponse) Reset() {
	*x = RequestFriendResponse{}
	mi := &file_openpak_account_v1_social_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestFriendResponse) ProtoMessage() {}

func (x *RequestFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_social_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestFriendResponse.ProtoReflect.Descriptor instead.
func (*RequestFriendResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_social_proto_rawDescGZIP(), []int{1}
}

func (x *RequestFriendResponse) GetFriendshipId() string {
	if x != nil {
		return x.FriendshipId
	}
	return ""
}

func (x *RequestFriendResponse) GetState() FriendState {
	if x != nil {
		return x.State
	}
	return FriendState_FRIEND_STATE_UNSPECIFIED
}

type AcceptFriendRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AddresseeId    string                 `protobuf:"bytes,1,opt,name=addressee_id,json=addresseeId,proto3" json:"addressee_id,omitempty"` // caller must be the addressee
	RequesterId    string                 `protobuf:"bytes,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AcceptFriendRequest) Reset() {
	*x = AcceptFriendRequest{}
	mi := &file_openpak_account_v1_social_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendRequest) ProtoMessage() {}

func (x *AcceptFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_social_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendRequest.ProtoReflect.Descriptor instead.
func (*AcceptFriendRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_social_proto_rawDescGZIP(), []int{2}
}

func (x *AcceptFriendRequest) GetAddresseeId() string {
	if x != nil {
		return x.AddresseeId
	}
	return ""
}

func (x *AcceptFriendRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *AcceptFriendRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type AcceptFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         FriendState            `protobuf:"varint,1,opt,name=state,proto3,enum=openpak.account.v1.FriendState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFriendResponse) Reset() {
	*x = AcceptFriendResponse{}
	mi := &file_openpak_account_v1_social_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendResponse) ProtoMessage() {}

func (x *AcceptFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_social_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendResponse.ProtoReflect.Descriptor instead.
func (*AcceptFriendResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_social_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptFriendResponse) GetState() FriendState {
	if x != nil {
		return x.State
	}
	return FriendState_FRIEND_STATE_UNSPECIFIED
}

type RemoveFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` // either side may remove
	OtherId       string                 `protobuf:"bytes,2,opt,name=other_id,json=otherId,proto3" json:"other_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFriendRequest) Reset() {
	*x = RemoveFriendRequest{}
	mi := &file_openpak_account_v1_social_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFriendRequest) ProtoMessage() {}

func (x *RemoveFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_social_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFriendRequest.ProtoReflect.Descriptor instead.
func (*RemoveFriendRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_social_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveFriendRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *RemoveFriendRequest) GetOtherId() string {
	if x != nil {
		return x.OtherId
	}
	return ""
}

type RemoveFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFriendResponse) Reset() {
	*x = RemoveFriendResponse{}
	mi := &file_openpak_account_v1_social_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFriendResponse) ProtoMessage() {}

func (x *RemoveFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_social_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFriendResponse.ProtoReflect.Descriptor instead.
func (*RemoveFriendResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_social_proto_rawDescGZIP(), []int{5}
}

type ListFriendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendsRequest) Reset() {
	*x = ListFriendsRequest{}
	mi := &file_openpak_account_v1_social_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsRequest) ProtoMessage() {}

func (x *ListFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_social_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsRequest.ProtoReflect.Descriptor instead.
func (*ListFriendsRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_social_proto_rawDescGZIP(), []int{6}
}

func (x *ListFriendsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type ListFriendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friends       []*Friend              `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendsResponse) Reset() {
	*x = ListFriendsResponse{}
	mi := &file_openpak_account_v1_social_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsResponse) ProtoMessage() {}

func (x *ListFriendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_social_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsResponse.ProtoReflect.Descriptor instead.
func (*ListFriendsResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_social_proto_rawDescGZIP(), []int{7}
}

func (x *ListFriendsResponse) GetFriends() []*Friend {
	if x != nil {
		return x.Friends
	}
	return nil
}

type Friend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Friend) Reset() {
	*x = Friend{}
	mi := &file_openpak_account_v1_social_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Friend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Friend) ProtoMessage() {}

func (x *Friend) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_social_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Friend.ProtoReflect.Descriptor instead.
func (*Friend) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_social_proto_rawDescGZIP(), []int{8}
}

func (x *Friend) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Friend) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type ListIncomingRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIncomingRequestsRequest) Reset() {
	*x = ListIncomingRequestsRequest{}
	mi := &file_openpak_account_v1_social_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIncomingRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIncomingRequestsRequest) ProtoMessage() {}

func (x *ListIncomingRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_social_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIncomingRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListIncomingRequestsRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_social_proto_rawDescGZIP(), []int{9}
}

func (x *ListIncomingRequestsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type ListOutgoingRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOutgoingRequestsRequest) Reset() {
	*x = ListOutgoingRequestsRequest{}
	mi := &file_openpak_account_v1_social_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOutgoingRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOutgoingRequestsRequest) ProtoMessage() {}

func (x *ListOutgoingRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_social_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOutgoingRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListOutgoingRequestsRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_social_proto_rawDescGZIP(), []int{10}
}

func (x *ListOutgoingRequestsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type ListOutgoingRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addressees    []*Friend              `protobuf:"bytes,1,rep,name=addressees,proto3" json:"addressees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOutgoingRequestsResponse) Reset() {
	*x = ListOutgoingRequestsResponse{}
	mi := &file_openpak_account_v1_social_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOutgoingRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOutgoingRequestsResponse) ProtoMessage() {}

func (x *ListOutgoingRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_social_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOutgoingRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListOutgoingRequestsResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_social_proto_rawDescGZIP(), []int{11}
}

func (x *ListOutgoingRequestsResponse) GetAddressees() []*Friend {
	if x != nil {
		return x.Addressees
	}
	return nil
}

type ListIncomingRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requesters    []*Friend              `protobuf:"bytes,1,rep,name=requesters,proto3" json:"requesters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIncomingRequestsResponse) Reset() {
	*x = ListIncomingRequestsResponse{}
	mi := &file_openpak_account_v1_social_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIncomingRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIncomingRequestsResponse) ProtoMessage() {}

func (x *ListIncomingRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_social_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIncomingRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListIncomingRequestsResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_social_proto_rawDescGZIP(), []int{12}
}

func (x *ListIncomingRequestsResponse) GetRequesters() []*Friend {
	if x != nil {
		return x.Requesters
	}
	return nil
}

type GetRelationshipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` // viewpoint
	OtherId       string                 `protobuf:"bytes,2,opt,name=other_id,json=otherId,proto3" json:"other_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelationshipRequest) Reset() {
	*x = GetRelationshipRequest{}
	mi := &file_openpak_account_v1_social_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelationshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelationshipRequest) ProtoMessage() {}

func (x *GetRelationshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_social_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelationshipRequest.ProtoReflect.Descriptor instead.
func (*GetRelationshipRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_social_proto_rawDescGZIP(), []int{13}
}

func (x *GetRelationshipRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetRelationshipRequest) GetOtherId() string {
	if x != nil {
		return x.OtherId
	}
	return ""
}

type GetRelationshipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relationship  Relationship           `protobuf:"varint,1,opt,name=relationship,proto3,enum=openpak.account.v1.Relationship" json:"relationship,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelationshipResponse) Reset() {
	*x = GetRelationshipResponse{}
	mi := &file_openpak_account_v1_social_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelationshipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelationshipResponse) ProtoMessage() {}

func (x *GetRelationshipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_social_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelationshipResponse.ProtoReflect.Descriptor instead.
func (*GetRelationshipResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_social_proto_rawDescGZIP(), []int{14}
}

func (x *GetRelationshipResponse) GetRelationship() Relationship {
	if x != nil {
		return x.Relationship
	}
	return Relationship_RELATIONSHIP_UNSPECIFIED
}

type CheckInteractionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Kind          InteractionKind        `protobuf:"varint,3,opt,name=kind,proto3,enum=openpak.account.v1.InteractionKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInteractionRequest) Reset() {
	*x = CheckInteractionRequest{}
	mi := &file_openpak_account_v1_social_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInteractionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInteractionRequest) ProtoMessage() {}

func (x *CheckInteractionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_social_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInteractionRequest.ProtoReflect.Descriptor instead.
func (*CheckInteractionRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_social_proto_rawDescGZIP(), []int{15}
}

func (x *CheckInteractionRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *CheckInteractionRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *CheckInteractionRequest) GetKind() InteractionKind {
	if x != nil {
		return x.Kind
	}
	return InteractionKind_INTERACTION_KIND_UNSPECIFIED
}

type CheckInteractionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason        DenialReason           `protobuf:"varint,2,opt,name=reason,proto3,enum=openpak.account.v1.DenialReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInteractionResponse) Reset() {
	*x = CheckInteractionResponse{}
	mi := &file_openpak_account_v1_social_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInteractionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInteractionResponse) ProtoMessage() {}

func (x *CheckInteractionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_social_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInteractionResponse.ProtoReflect.Descriptor instead.
func (*CheckInteractionResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_social_proto_rawDescGZIP(), []int{16}
}

func (x *CheckInteractionResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckInteractionResponse) GetReason() DenialReason {
	if x != nil {
		return x.Reason
	}
	return DenialReason_DENIAL_REASON_UNSPECIFIED
}

type BlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockerId     string                 `protobuf:"bytes,1,opt,name=blocker_id,json=blockerId,proto3" json:"blocker_id,omitempty"`
	BlockedId     string                 `protobuf:"bytes,2,opt,name=blocked_id,json=blockedId,proto3" json:"blocked_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockRequest) Reset() {
	*x = BlockRequest{}
	mi := &file_openpak_account_v1_social_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRequest) ProtoMessage() {}

func (x *BlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_social_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRequest.ProtoReflect.Descriptor instead.
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_social_proto_rawDescGZIP(), []int{17}
}

func (x *BlockRequest) GetBlockerId() string {
	if x != nil {
		return x.BlockerId
	}
	return ""
}

func (x *BlockRequest) GetBlockedId() string {
	if x != nil {
		return x.BlockedId
	}
	return ""
}

type BlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockResponse) Reset() {
	*x = BlockResponse{}
	mi := &file_openpak_account_v1_social_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockResponse) ProtoMessage() {}

func (x *BlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_social_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockResponse.ProtoReflect.Descriptor instead.
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_social_proto_rawDescGZIP(), []int{18}
}

type UnblockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockerId     string                 `protobuf:"bytes,1,opt,name=blocker_id,json=blockerId,proto3" json:"blocker_id,omitempty"`
	BlockedId     string                 `protobuf:"bytes,2,opt,name=blocked_id,json=blockedId,proto3" json:"blocked_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockRequest) Reset() {
	*x = UnblockRequest{}
	mi := &file_openpak_account_v1_social_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockRequest) ProtoMessage() {}

func (x *UnblockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_social_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockRequest.ProtoReflect.Descriptor instead.
func (*UnblockRequest) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_social_proto_rawDescGZIP(), []int{19}
}

func (x *UnblockRequest) GetBlockerId() string {
	if x != nil {
		return x.BlockerId
	}
	return ""
}

func (x *UnblockRequest) GetBlockedId() string {
	if x != nil {
		return x.BlockedId
	}
	return ""
}

type UnblockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockResponse) Reset() {
	*x = UnblockResponse{}
	mi := &file_openpak_account_v1_social_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockResponse) ProtoMessage() {}

func (x *UnblockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openpak_account_v1_social_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockResponse.ProtoReflect.Descriptor instead.
func (*UnblockResponse) Descriptor() ([]byte, []int) {
	return file_openpak_account_v1_social_proto_rawDescGZIP(), []int{20}
}

var File_openpak_account_v1_social_proto protoreflect.FileDescriptor

const file_openpak_account_v1_social_proto_rawDesc = "" +
	"\n" +
	"\x1fopenpak/account/v1/social.proto\x12\x12openpak.account.v1\"\x85\x01\n" +
	"\x14RequestFriendRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\tR\vrequesterId\x12!\n" +
	"\faddressee_id\x18\x02 \x01(\tR\vaddresseeId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"s\n" +
	"\x15RequestFriendResponse\x12#\n" +
	"\rfriendship_id\x18\x01 \x01(\tR\ffriendshipId\x125\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1f.openpak.account.v1.FriendStateR\x05state\"\x84\x01\n" +
	"\x13AcceptFriendRequest\x12!\n" +
	"\faddressee_id\x18\x01 \x01(\tR\vaddresseeId\x12!\n" +
	"\frequester_id\x18\x02 \x01(\tR\vrequesterId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"M\n" +
	"\x14AcceptFriendResponse\x125\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1f.openpak.account.v1.FriendStateR\x05state\"O\n" +
	"\x13RemoveFriendRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x19\n" +
	"\bother_id\x18\x02 \x01(\tR\aotherId\"\x16\n" +
	"\x14RemoveFriendResponse\"3\n" +
	"\x12ListFriendsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"K\n" +
	"\x13ListFriendsResponse\x124\n" +
	"\afriends\x18\x01 \x03(\v2\x1a.openpak.account.v1.FriendR\afriends\"J\n" +
	"\x06Friend\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"<\n" +
	"\x1bListIncomingRequestsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"<\n" +
	"\x1bListOutgoingRequestsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"Z\n" +
	"\x1cListOutgoingRequestsResponse\x12:\n" +
	"\n" +
	"addressees\x18\x01 \x03(\v2\x1a.openpak.account.v1.FriendR\n" +
	"addressees\"Z\n" +
	"\x1cListIncomingRequestsResponse\x12:\n" +
	"\n" +
	"requesters\x18\x01 \x03(\v2\x1a.openpak.account.v1.FriendR\n" +
	"requesters\"R\n" +
	"\x16GetRelationshipRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x19\n" +
	"\bother_id\x18\x02 \x01(\tR\aotherId\"_\n" +
	"\x17GetRelationshipResponse\x12D\n" +
	"\frelationship\x18\x01 \x01(\x0e2 .openpak.account.v1.RelationshipR\frelationship\"\x8a\x01\n" +
	"\x17CheckInteractionRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x127\n" +
	"\x04kind\x18\x03 \x01(\x0e2#.openpak.account.v1.InteractionKindR\x04kind\"n\n" +
	"\x18CheckInteractionResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x128\n" +
	"\x06reason\x18\x02 \x01(\x0e2 .openpak.account.v1.DenialReasonR\x06reason\"L\n" +
	"\fBlockRequest\x12\x1d\n" +
	"\n" +
	"blocker_id\x18\x01 \x01(\tR\tblockerId\x12\x1d\n" +
	"\n" +
	"blocked_id\x18\x02 \x01(\tR\tblockedId\"\x0f\n" +
	"\rBlockResponse\"N\n" +
	"\x0eUnblockRequest\x12\x1d\n" +
	"\n" +
	"blocker_id\x18\x01 \x01(\tR\tblockerId\x12\x1d\n" +
	"\n" +
	"blocked_id\x18\x02 \x01(\tR\tblockedId\"\x11\n" +
	"\x0fUnblockResponse*\xe8\x01\n" +
	"\fRelationship\x12\x1c\n" +
	"\x18RELATIONSHIP_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11RELATIONSHIP_NONE\x10\x01\x12!\n" +
	"\x1dRELATIONSHIP_PENDING_INCOMING\x10\x02\x12!\n" +
	"\x1dRELATIONSHIP_PENDING_OUTGOING\x10\x03\x12\x18\n" +
	"\x14RELATIONSHIP_FRIENDS\x10\x04\x12 \n" +
	"\x1cRELATIONSHIP_BLOCKED_BY_SELF\x10\x05\x12!\n" +
	"\x1dRELATIONSHIP_BLOCKED_BY_OTHER\x10\x06*\x8d\x01\n" +
	"\x0fInteractionKind\x12 \n" +
	"\x1cINTERACTION_KIND_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19INTERACTION_KIND_DISCOVER\x10\x01\x12\x1b\n" +
	"\x17INTERACTION_KIND_INVITE\x10\x02\x12\x1c\n" +
	"\x18INTERACTION_KIND_MESSAGE\x10\x03*\xbe\x01\n" +
	"\fDenialReason\x12\x1d\n" +
	"\x19DENIAL_REASON_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15DENIAL_REASON_ALLOWED\x10\x01\x12\x19\n" +
	"\x15DENIAL_REASON_BLOCKED\x10\x02\x12\x1d\n" +
	"\x19DENIAL_REASON_NOT_FRIENDS\x10\x03\x12\"\n" +
	"\x1eDENIAL_REASON_ACCOUNT_INACTIVE\x10\x04\x12\x16\n" +
	"\x12DENIAL_REASON_SELF\x10\x05*`\n" +
	"\vFriendState\x12\x1c\n" +
	"\x18FRIEND_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14FRIEND_STATE_PENDING\x10\x01\x12\x19\n" +
	"\x15FRIEND_STATE_ACCEPTED\x10\x022\x87\b\n" +
	"\x06Social\x12d\n" +
	"\rRequestFriend\x12(.openpak.account.v1.RequestFriendRequest\x1a).openpak.account.v1.RequestFriendResponse\x12a\n" +
	"\fAcceptFriend\x12'.openpak.account.v1.AcceptFriendRequest\x1a(.openpak.account.v1.AcceptFriendResponse\x12a\n" +
	"\fRemoveFriend\x12'.openpak.account.v1.RemoveFriendRequest\x1a(.openpak.account.v1.RemoveFriendResponse\x12^\n" +
	"\vListFriends\x12&.openpak.account.v1.ListFriendsRequest\x1a'.openpak.account.v1.ListFriendsResponse\x12y\n" +
	"\x14ListIncomingRequests\x12/.openpak.account.v1.ListIncomingRequestsRequest\x1a0.openpak.account.v1.ListIncomingRequestsResponse\x12y\n" +
	"\x14ListOutgoingRequests\x12/.openpak.account.v1.ListOutgoingRequestsRequest\x1a0.openpak.account.v1.ListOutgoingRequestsResponse\x12j\n" +
	"\x0fGetRelationship\x12*.openpak.account.v1.GetRelationshipRequest\x1a+.openpak.account.v1.GetRelationshipResponse\x12m\n" +
	"\x10CheckInteraction\x12+.openpak.account.v1.CheckInteractionRequest\x1a,.openpak.account.v1.CheckInteractionResponse\x12L\n" +
	"\x05Block\x12 .openpak.account.v1.BlockRequest\x1a!.openpak.account.v1.BlockResponse\x12R\n" +
	"\aUnblock\x12\".openpak.account.v1.UnblockRequest\x1a#.openpak.account.v1.UnblockResponseB4Z2openpak/account/proto/openpak/account/v1;accountv1b\x06proto3"

var (
	file_openpak_account_v1_social_proto_rawDescOnce sync.Once
	file_openpak_account_v1_social_proto_rawDescData []byte
)

func file_openpak_account_v1_social_proto_rawDescGZIP() []byte {
	file_openpak_account_v1_social_proto_rawDescOnce.Do(func() {
		file_openpak_account_v1_social_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openpak_account_v1_social_proto_rawDesc), len(file_openpak_account_v1_social_proto_rawDesc)))
	})
	return file_openpak_account_v1_social_proto_rawDescData
}

var file_openpak_account_v1_social_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_openpak_account_v1_social_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_openpak_account_v1_social_proto_goTypes = []any{
	(Relationship)(0),                    // 0: openpak.account.v1.Relationship
	(InteractionKind)(0),                 // 1: openpak.account.v1.InteractionKind
	(DenialReason)(0),                    // 2: openpak.account.v1.DenialReason
	(FriendState)(0),                     // 3: openpak.account.v1.FriendState
	(*RequestFriendRequest)(nil),         // 4: openpak.account.v1.RequestFriendRequest
	(*RequestFriendResponse)(nil),        // 5: openpak.account.v1.RequestFriendResponse
	(*AcceptFriendRequest)(nil),          // 6: openpak.account.v1.AcceptFriendRequest
	(*AcceptFriendResponse)(nil),         // 7: openpak.account.v1.AcceptFriendResponse
	(*RemoveFriendRequest)(nil),          // 8: openpak.account.v1.RemoveFriendRequest
	(*RemoveFriendResponse)(nil),         // 9: openpak.account.v1.RemoveFriendResponse
	(*ListFriendsRequest)(nil),           // 10: openpak.account.v1.ListFriendsRequest
	(*ListFriendsResponse)(nil),          // 11: openpak.account.v1.ListFriendsResponse
	(*Friend)(nil),                       // 12: openpak.account.v1.Friend
	(*ListIncomingRequestsRequest)(nil),  // 13: openpak.account.v1.ListIncomingRequestsRequest
	(*ListOutgoingRequestsRequest)(nil),  // 14: openpak.account.v1.ListOutgoingRequestsRequest
	(*ListOutgoingRequestsResponse)(nil), // 15: openpak.account.v1.ListOutgoingRequestsResponse
	(*ListIncomingRequestsResponse)(nil), // 16: openpak.account.v1.ListIncomingRequestsResponse
	(*GetRelationshipRequest)(nil),       // 17: openpak.account.v1.GetRelationshipRequest
	(*GetRelationshipResponse)(nil),      // 18: openpak.account.v1.GetRelationshipResponse
	(*CheckInteractionRequest)(nil),      // 19: openpak.account.v1.CheckInteractionRequest
	(*CheckInteractionResponse)(nil),     // 20: openpak.account.v1.CheckInteractionResponse
	(*BlockRequest)(nil),                 // 21: openpak.account.v1.BlockRequest
	(*BlockResponse)(nil),                // 22: openpak.account.v1.BlockResponse
	(*UnblockRequest)(nil),               // 23: openpak.account.v1.UnblockRequest
	(*UnblockResponse)(nil),              // 24: openpak.account.v1.UnblockResponse
}
var file_openpak_account_v1_social_proto_depIdxs = []int32{
	3,  // 0: openpak.account.v1.RequestFriendResponse.state:type_name -> openpak.account.v1.FriendState
	3,  // 1: openpak.account.v1.AcceptFriendResponse.state:type_name -> openpak.account.v1.FriendState
	12, // 2: openpak.account.v1.ListFriendsResponse.friends:type_name -> openpak.account.v1.Friend
	12, // 3: openpak.account.v1.ListOutgoingRequestsResponse.addressees:type_name -> openpak.account.v1.Friend
	12, // 4: openpak.account.v1.ListIncomingRequestsResponse.requesters:type_name -> openpak.account.v1.Friend
	0,  // 5: openpak.account.v1.GetRelationshipResponse.relationship:type_name -> openpak.account.v1.Relationship
	1,  // 6: openpak.account.v1.CheckInteractionRequest.kind:type_name -> openpak.account.v1.InteractionKind
	2,  // 7: openpak.account.v1.CheckInteractionResponse.reason:type_name -> openpak.account.v1.DenialReason
	4,  // 8: openpak.account.v1.Social.RequestFriend:input_type -> openpak.account.v1.RequestFriendRequest
	6,  // 9: openpak.account.v1.Social.AcceptFriend:input_type -> openpak.account.v1.AcceptFriendRequest
	8,  // 10: openpak.account.v1.Social.RemoveFriend:input_type -> openpak.account.v1.RemoveFriendRequest
	10, // 11: openpak.account.v1.Social.ListFriends:input_type -> openpak.account.v1.ListFriendsRequest
	13, // 12: openpak.account.v1.Social.ListIncomingRequests:input_type -> openpak.account.v1.ListIncomingRequestsRequest
	14, // 13: openpak.account.v1.Social.ListOutgoingRequests:input_type -> openpak.account.v1.ListOutgoingRequestsRequest
	17, // 14: openpak.account.v1.Social.GetRelationship:input_type -> openpak.account.v1.GetRelationshipRequest
	19, // 15: openpak.account.v1.Social.CheckInteraction:input_type -> openpak.account.v1.CheckInteractionRequest
	21, // 16: openpak.account.v1.Social.Block:input_type -> openpak.account.v1.BlockRequest
	23, // 17: openpak.account.v1.Social.Unblock:input_type -> openpak.account.v1.UnblockRequest
	5,  // 18: openpak.account.v1.Social.RequestFriend:output_type -> openpak.account.v1.RequestFriendResponse
	7,  // 19: openpak.account.v1.Social.AcceptFriend:output_type -> openpak.account.v1.AcceptFriendResponse
	9,  // 20: openpak.account.v1.Social.RemoveFriend:output_type -> openpak.account.v1.RemoveFriendResponse
	11, // 21: openpak.account.v1.Social.ListFriends:output_type -> openpak.account.v1.ListFriendsResponse
	16, // 22: openpak.account.v1.Social.ListIncomingRequests:output_type -> openpak.account.v1.ListIncomingRequestsResponse
	15, // 23: openpak.account.v1.Social.ListOutgoingRequests:output_type -> openpak.account.v1.ListOutgoingRequestsResponse
	18, // 24: openpak.account.v1.Social.GetRelationship:output_type -> openpak.account.v1.GetRelationshipResponse
	20, // 25: openpak.account.v1.Social.CheckInteraction:output_type -> openpak.account.v1.CheckInteractionResponse
	22, // 26: openpak.account.v1.Social.Block:output_type -> openpak.account.v1.BlockResponse
	24, // 27: openpak.account.v1.Social.Unblock:output_type -> openpak.account.v1.UnblockResponse
	18, // [18:28] is the sub-list for method output_type
	8,  // [8:18] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_openpak_account_v1_social_proto_init() }
func file_openpak_account_v1_social_proto_init() {
	if File_openpak_account_v1_social_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openpak_account_v1_social_proto_rawDesc), len(file_openpak_account_v1_social_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_openpak_account_v1_social_proto_goTypes,
		DependencyIndexes: file_openpak_account_v1_social_proto_depIdxs,
		EnumInfos:         file_openpak_account_v1_social_proto_enumTypes,
		MessageInfos:      file_openpak_account_v1_social_proto_msgTypes,
	}.Build()
	File_openpak_account_v1_social_proto = out.File
	file_openpak_account_v1_social_proto_goTypes = nil
	file_openpak_account_v1_social_proto_depIdxs = nil
}
